### ISSUE TITLE
*** 4oD DOWNLOADING IS BROKEN - NO FIX AVAILABLE ***

### ISSUE THREAD

**Issue by willson556** [GetiPlayerAutomator/get-iplayer-automator#241]
_From [dinkypumpkin](https://code.google.com/u/dinkypumpkin/) on July 07, 2013 15:19:22_

As of 2013-07-01 (approx.) 4oD programmes are no longer available to GiA due to changes in C4 services.  The 4oD support will remain in GiA for the time being in case the situation changes.  If it does not change, expect the 4oD features to be disabled and possibly disappear in future releases.

DO NOT report any further 4oD download failures - you will not receive a response.  Also do not post any queries, follow-ups, commiserations, etc., to this thread.  This issue has been posted solely as a notice to users.

if you find that you *CAN* download any 4oD programme, please create a new issue and report the exact programme name, series number, episode number and UTC time that you downloaded.

_Original issue: http://code.google.com/p/get-iplayer-automator/issues/detail?id=247_

**Comment by dinkypumpkin** [comment]
Dead 4oD code removed in d5d7037de453fecd11b7d186bd310a5dfc1ee123
