### ISSUE TITLE
Feature Request: Checkbox to automatically incorporate subs within the mp4 as soft subs so I can see them on my AppleTV

### ISSUE THREAD

**Issue by willson556** [GetiPlayerAutomator/get-iplayer-automator#371]
_From [Tu2As...@gmail.com](https://code.google.com/u/116987815120350660486/) on May 15, 2014 02:28:08_

Feature Request: Checkbox to automatically incorporate subs within the mp4 as soft subs so I can see them on my AppleTV

ffmpeg -i "<SOURCE.mp4>" -i "<SOURCE.srt>" -c:s mov_text -metadata:s:s:0 language=eng -c:v copy -c:a copy "<DESTINATION_WITH_INCORPORATED_SOFTSUBS.mp4>"

_Original issue: http://code.google.com/p/get-iplayer-automator/issues/detail?id=379_

**Comment by hugofalkman** [comment]
Hi wilson and dinkypumpkin.

English not being my native language it's enormously helpful for me to include the English subtitles in my GiA downloads.

I have now been using Subler for about a year to add the subtitles to the iTunes mp4 files. There're a lot of repetitive tasks that GiA could help automating in the spirit of the original automation of Get iPlayer. For every single GiA download I go through these steps:

(0. I always keep the Subler queue window open behind iTunes in its desktop.)
1. In iTunes I right click on the show and choose Show in Finder.
2. In Finder I open the mp4 file in Subler
3. In Subler I click on the plus sign to add a track and then choose the .srt file in the GiA download folder.
4. In Subler I click on Send to Queue. This closes the mp4 Subler window.
5. In the Subler queue window that has remained open I first click on the arrow to to save the mp4 file(s) with the subtitle track included and then right click on the queue to remove completed entries.
6.  I go back in Finder and delete the mp4 and srt files in the GiA download folder.

Two comments:

It has only happened to me once that I needed to go back and in Subler add an offset to the subtitle track for a BBC show. But to know what the offset should be I need anyway to go through the routine above and then run the show to estimate how large the offset should be. So in a GiA automation implementation of this process -- the only thing needed to support offsets would be a properly worded warning message to use Subler to add an offset if the subtitles are off.

It is not uncommon for both BBC and ITV to miss supplying the .srt file when the show first appears. So far they have always fixed this 24 hours later. So its important with a good error message (preferably aborting the download) if there is no .srt file. (I sometimes wait months before I watch a downloaded show -- that I can do that is one of many advantages with GiA.)
