### ISSUE TITLE
Get Started guide in readme

### ISSUE THREAD

**Issue by JohnMcLear** [GetiPlayerAutomator/get-iplayer-automator#403]
y u no have?

**Comment by jimthing** [comment]
As Blue Peter says, 'here's one I made earlier' ;-) ... 

**Quick Start Guide: 
1) Download and open the Get iPlayer app, making sure the programme Cache has refreshed, which it will do if the app is not opened for over two hours (press the "Refresh Cache" button, if not). Wait for refresh to finish. If first use of app, then open the Prefs (⌘,) to check and select your options of choice.

2) Open the BBC iPlayer webpage in your browser (Chrome/Safari recommended, to allow "Use Current Webpage" feature, see below). 

3) Quick options for finding programmes to download (either/both option methods can be used):

3.1) Go through the BBC iPlayer schedules website pages at least once each week (or whatever time you choose) for the channels you watch. ITV channels can also be seen using the BBC schedules page. (To avoid disappointment, doing this weekly is still recommended, as a few programmes will not be available past 7-days, despite 30-days for most of them). 

3.2) Alternatively, just search the BBC iPlayer website ad hoc for the programme you want, and open the show's programme page (e.g. http://www.bbc.co.uk/iplayer/episode/b04ykm2t/the-programme-series-1-3-programme-episode-name ). 

4) In the Get iPlayer app, search for the programme title, click on it to select it, then add to the Download Queue by pressing "Add To Queue" button. (Only programmes from last 7 days are searchable, though many running series' will have the past episodes appear in search as well.) Alternatively, if not found in search, with the programme page open in the front most browser window, press "Use Current Webpage" button to add to Download Queue. 

5) When a programme has been added to the Download Queue, press the green Start button. This can even be done while you repeat the steps above to search for other programmes. 

6) All downloaded programmes appear in a Download History file, which can be accessed when nothing is currently downloading (⌃⌘H). If a file fails to download/convert correctly, delete it from here AND your download location folder FIRST, before reattempting. 

7) If a BBC programme fails, first check the BBC iPlayer "Help & FAQ" section for programme issues (try again later, or report to BBC using the "Contact Us" on the website, if desired). Try other programmes in the series/day/channel to see if they download, before reporting issue to GiA's Github. 

Note: This is just a quick start guide, and does not attempt to explain the PVR/Series-Link functionalities more experienced users may use. Some steps above may be omitted as per personal preference. **
