### ISSUE TITLE
Add "Skip when shuffling" iTunes option to radio programmes

### ISSUE THREAD

**Issue by GrahamFord** [GetiPlayerAutomator/get-iplayer-automator#439]
Is it possible for GetiPlayerAutomator to mark radio downloads as Audiobooks so that iTunes will remember the playback position and will skip them when shuffling?

**Comment by Gedoe** [comment]
It works if you change the 'media kind' from music to podcast. Right click on a downloaded file and choose 'Get info' and look under 'Options'.
