### ISSUE TITLE
Radio4 programme fails to be found in search.

### ISSUE THREAD

**Issue by ukmoose** [GetiPlayerAutomator/get-iplayer-automator#452]
A show that was on today, fails to be found in search.  
The Radio Show is Self Orbits CERN  http://www.bbc.co.uk/programmes/b04wtgjq  
If you do a "Use current webpage" "process PID"  shows up as "Self Orbits CERN, A Naked Lunch" copying that into the search still fails to find anything.

**Comment by dinkypumpkin** [comment]
Cannot reproduce.  Works fine here, searching for "Orbits".  Remove punctuation if using title generated by "Process PID" - they hyphen will break search. And make sure BBC Radio is selected in preferences

**Comment by dinkypumpkin** [comment]
And force a cache update, just in case.
