### ISSUE TITLE
Failure to download - inconsistent at best

### ISSUE THREAD

**Issue by xebgoc** [GetiPlayerAutomator/get-iplayer-automator#456]
Beginning on Friday 16th January, downloading has been inconsistent but has mostly failed. The error message that is coming up is simply "Problem Unknown. Please submit a bug report from the application menu"  (I thought that that mechanism no longer worked?)

In particular, episode 3 of Musketeers (PID 1608 ) continues to fail. 

I initially had trouble with the Friday night, 16th January episodes of The Graham Norton Show (PID 1574) and QI (PID 1248), though the last two eventually downloaded on Saturday morning and on Sunday (the 18th) I've gotten both an ITV & a BBC1 show to download on the first attempt. 

I am running the most up-to-date version of GiPA, though have not upgraded to Yosemite. 
I have tried the provided proxy as well as substituted proxies that I knew were working. 
I have tried "use current webpage" and the search function.

**Comment by Sircam19** [comment]
I have noticed much of the same thing. I had problems downloading the Musketeer's episode referred to, but was eventually able to download it  as an audio described version.

**Comment by jimthing** [comment]
Musketeer's ep3, I cannot get either: get "None of the download formats..." 

I've tried HD & Very High, both plain and with Audio Described: all show same message above. 

Reported to Beeb, we'll see. They always seem to screw-up one episode per series, don't they, as some kind of anti-piracy fuck-off-your-users measure, it's uncanny! :-|

**Comment by mostlyotter** [comment]
Log for attempt to download The Musketeers 203 https://gist.github.com/mostlyotter/cd85f24a604584aeda40

**Comment by dinkypumpkin** [comment]
The fix for this problem will be in the next GiA release.  If you also use get_player itself, there is a workaround:

https://github.com/get-iplayer/get_iplayer/issues/115

**Comment by jimthing** [comment]
I can confirm what's already known: the Beeb just responded to my request confirming they do not have the problem. So as Dinky said, this is now an get_player problem for the next GiA release.
