### ISSUE TITLE
Where is 'Show Downloaded Shows in Search' preference shown?

### ISSUE THREAD

**Issue by upekshapriya** [GetiPlayerAutomator/get-iplayer-automator#459]
I can't see where the Advanced preference 'Show Downloaded Shows in Search' is shown when searching. I can't see it in the info window or anywhere else :)

**Comment by dinkypumpkin** [comment]
The preference setting controls the content of the search results.  It doesn't have any visible manifestation of its own.

**Comment by upekshapriya** [comment]
Thanks. Seems obvious now you say it!
