### ISSUE TITLE
Unresumable File @ Search Issue

### ISSUE THREAD

**Issue by Sircam19** [GetiPlayerAutomator/get-iplayer-automator#462]
Not sure if this is an episode specific issue or the sign of things to come. 

"Lance Armstrong: The Road Ahead" (bo52mjkd) cannot be completely downloaded. It starts and then after a few moments fails, and this happens repeatedly even after trying to resume by removing the partial downloaded file as suggested / recommended in the log. Also,  although the episode was recently broadcasted it doesn't appear via a regular search but by using the "use current webpage" option. 

Just thought I would flag to give a "heads up"

**Comment by dinkypumpkin** [comment]
Cannot reproduce - works fine here.  A few BBC News Channel programmes - such as this one - are mislabelled upstream.  Nothing you can do except download directly.

**Comment by malcolmasia** [comment]
This issue is not solved. I have the same problem. BBC program files download about 20 to 25% then stall. It then goes into the initialising stage repeatedly before failing with the problem window opening.
(ITV files are not affected).
