### ISSUE TITLE
BBC program downloads failing after 20 to 30% downloaded. 

### ISSUE THREAD

**Issue by malcolmasia** [GetiPlayerAutomator/get-iplayer-automator#463]
BBC show downloads are failing after 20 to 30% downloaded, after which they stall and go into the initialising stage repeatedly before failing with the problem/failure window opening.
(ITV files are not affected).

**Comment by dinkypumpkin** [comment]
No usable information provided.  Read the Reporting  Issues and Verbose Log pages in the wiki and try again.
