### ISSUE TITLE
Cache will not update, on board snag report won't send, and in-app update fails

### ISSUE THREAD

**Issue by pmhird** [GetiPlayerAutomator/get-iplayer-automator#475]
Hi there,

I'm running 1.8.5 on 10.9.4 and can't get the GIA to update the cache. It won't work at all with the provided proxy, and when I key in a manual one that worked earlier fine earlier today, it tests ok, but still the cache will not update. i tried to use the on-board snag reporter but that wouldn't send, and I tried the in-app updater with no success either. Is there an external server that has somehow become not available? Or is this just a strange proxy problem, that still seems to return "test ok" on the proxy? I have similar results on my other machine running 1.3.7.1 on 10.6.8, the app just hangs forever on the "updating tv feed" line. Any help appreciated.

**Comment by larryy** [comment]
Just FYI, last night it was taking GiA a very long time to update the cache.  I quit and relaunched with no effect.  But I went away and did something else and it eventually finished.  This sort of thing seems to happen once in a while.  YMMV.

**Comment by mostlyotter** [comment]
If I can't reach the GiA page at tom-tech.com, I know there will be no provided proxy and that I need to uncheck Quick Caching in the GiA preferences. Both seem to depend on that server. I'd guess other functions do too.

**Comment by dinkypumpkin** [comment]
As mostlyotter said, the server was dead for a few hours.
