### ISSUE TITLE
BBC TV programmes failing to download

### ISSUE THREAD

**Issue by fabmini** [GetiPlayerAutomator/get-iplayer-automator#476]
As of today I'm no longer able to download BBC TV programmes using Get iPlayer Automator. It takes an age to initialise, and then I get an error that the download has failed (problem unknown, submit bug report etc.). I'm running on OS 10.10.2, GIA version 1.8.5 (1735), through Overplay SmartDNS.
Have tried computer restart, modem restart, GIA restart, nothing's helping. Haven't had problems until today. Am still able to access BBC iPlayer website, and BBC radio programmes download fine.

Unfortunately I have no clue how to attach a log file to this message: I have followed the necessary instructions carefully, but according to GitHub you can only attach images, not TextEdit files.
This is undoubtedly down to me being a first-time user of this platform, so I apologise in advance if I'm doing anything wrong.

**Comment by larryy** [comment]
FYI, fabmini, the problem was either transient or is happening on your end.  I just downloaded a new program (Burk and Hare) with no problems.  I'm on Mac OS X 10.9.5, GiA 1.8.5 (1735), BolehVPN.

**Comment by dinkypumpkin** [comment]
You didn't follow the instructions as carefully as you claim since they very clearly do not tell you to attach a log file to your post.  My guess is that you can blame your "smart" DNS.  It wouldn't be the first time, but unless you post your log in a gist as instructed, nobody can say.
