### ISSUE TITLE
ITV programme Mr Selfridge won't download

### ISSUE THREAD

**Issue by upekshapriya** [GetiPlayerAutomator/get-iplayer-automator#477]
Trying to download the latest Mr Selfridge programme - I get the message 'Problem unknown'. See log at  https://gist.github.com/upekshapriya/65811e399acaf621a11f

**Comment by Littlerock53** [comment]
Same problem. 
Download works with setting in preferences: I
TV Format: Flash - Standard
doesn't work when ITV Format = Flash - High

**Comment by upekshapriya** [comment]
It's working now. I guess it was a server problem after all.
