### ISSUE TITLE
Anyone else having trouble with ITV lately?

### ISSUE THREAD

**Issue by pmhird** [GetiPlayerAutomator/get-iplayer-automator#478]
My get_iplayer automator is working absolutely fine for BBC and BBC radio but ITV shows just seem to hang the programme at the "Retrieving Programme Metadata" stage. It could be a proxy issue, but I have tried quite a few and tested them with BBC programmes and they work. 

There's not much point attaching the verbose log as it just gets no further than:

"INFO: Requesting Auth."

Any ideas? I am overseas using a proxy and using GIA 1.3.7.1 on OSX 10.5.8.

Thanks,

PH

**Comment by mostlyotter** [comment]
You don't say which ITV programmes, but no problem here recently and just now downloaded ten assorted ITV episodes, using the provided proxy with GIA 1.3.7.1 on 10.6.8.

**Comment by stickenhoffen** [comment]
Yep, had the same. Non-UK related I think, seemed to work fine with a tunnel, but proxy seems good now. Glitch in the matrix? :)

**Comment by pmhird** [comment]
Yes mine seems to have resumed normal service, although i didn�t change any settings. Although the process was hanging at �converting� when it did eventually download- I solved that by re-downloading the ffmpeg file and replacing it in GIA package contents. Now ITV seems fine.
