### ISSUE TITLE
Forcing GiA downloads to utilise higher audio settings ?

### ISSUE THREAD

**Issue by MarcelProust** [GetiPlayerAutomator/get-iplayer-automator#480]
Most R4 programmes come in at 128kbps, but R3 Drama usually downloads at 317kbps (e.g. 'The Portrait of Dorian Gray’, TX12/04/15).

Is there any way GiA can force the choice of bit rate, or is this entirely the down to the broadcaster ?

**Comment by dinkypumpkin** [comment]
R3 is the only station with 320k on-demand audio. 128k is the best available for other stations.

**Comment by MarcelProust** [comment]
Many thanks for clarification.
