### ISSUE TITLE
Show official minutes for each program downloaded

### ISSUE THREAD

**Issue by pstibbons** [GetiPlayerAutomator/get-iplayer-automator#481]
Would like to be able to compare the downloaded minutes with the official minutes for each program.  It would be convenient.  Thanks.

**Comment by dinkypumpkin** [comment]
Use the Info button in search results to see listed episode duration, or else go to the episode's page in the related web site.  However, the listed durations are virtually useless for determining whether or not a download is complete.  Listed durations are only shown to the nearest minute, and they may vary by more than a minute from the duration of the downloaded file.  Some radio programmes may have the full duration but still be truncated by the BBC (though these are typically repaired within a few days).  The only way to be certain a download is complete is to check the end of the file in a media player.

**Comment by pstibbons** [comment]
Hello,

Thanks for you're reply.  As I said, it would very convenient to have the
official count side by side with the download count in the app.  An error
of one minute would not be catastrophic.

Alan

**Comment by dinkypumpkin** [comment]
You missed the point. It wouldn't be catastrophic, but you wouldn't be very happy to find that you're missing the last couple of minutes of a programme even though the listed duration and downloaded duration were virtually the same - which can happen  However, I'll reopen this issue and leave it for Thomas or somebody else to consider.  It's obviously :thumbsdown: from me, though.  I don't want to clutter GiA with useless information that is already available by other means.

**Comment by pstibbons** [comment]
Okay, many thanks.  Perhaps it could be an option turned off, by default,
if at all possible.
