### ISSUE TITLE
ITV downloads broken since May 22 2015

### ISSUE THREAD

**Issue by MrGrumpy66** [GetiPlayerAutomator/get-iplayer-automator#484]
Can't get any ITV programs to download, it has been problematic for a while, but now refuses to download anything. 
Tried uninstalling and re-installng back to 1.83, but no change.
Using Cactus VPN (DNS Relocator) - Itv player website works fine.
Anyone else seeing issues?
Any Ideas?
OSX 10.10.3 - 2015 MacMini
Log from 1.84

Unreadable log spew moved to:

https://gist.github.com/anonymous/7e727689f8910bf9439b

**Comment by dinkypumpkin** [comment]
You may be Mr Grumpy, but you're not half as grumpy as I am when people refuse to [follow the instructions](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Reporting-Issues) for reporting issues and instead pollute the issue tracker with unreadable log spew.

Don't roll back to old versions.  You're wasting your time.

You are likely afflicted with either poor upstream connectivity or a duff VPN.  Once the first attempt fails and produces a corrupted file, the subsequent attempts will usually fail.  Delete any partial downloads and try again.  If it still doesn't work, perhaps try another VPN.  Whatever the cause, there is nothing GiA can do about it.  GiA + ITV works fine in the UK.
