### ISSUE TITLE
Series-Link to Queue misses most programmes out when asked to queue

### ISSUE THREAD

**Issue by ko7** [GetiPlayerAutomator/get-iplayer-automator#486]
GIA Version 1.8.5 (1735)
OSX 10.8.5
Problem: When Series-Link to Queue button is clicked, most programmes that are in the PVR series list do not get added to the download queue. This first occurred yesterday (6June).

E.G. I noticed that the latest "The Graham Norton Show" Series 17 Episode 9 (2015-06-05) wouldn't get added to the download queue when the TV Network in the PVR Manager Series-Link showed "The Graham Norton Show" as BBC ONE which it has done for many months, however when I changed the TV Network to (star) *    Series-Link automatically added it to the download queue. I then noticed that via the search for a program field that, "The Graham Norton Show" was now on TV Network as BBC One Cambridgeshire.

This is also occurring with other programs as well.

Do I need to change all my Series-Link TV Network to a (star) * so that I can get downloads added via the Series-Link or is there a fix to this that I should be aware of?

Thank you for your time in advance.

**Comment by dinkypumpkin** [comment]
For now, make TV Network = "*" for any programmes that fail with Series-Link to Queue.  I assume you have Quick Caching enabled.  Thomas is creating the cache file with the local BBC One variants (e.g., Cambridgeshire) included, though that is not the default with the latest get_iplayer.  This can probably be fixed for next release, but use the workaround for now.

**Comment by ko7** [comment]
I do have Quick Caching enabled.
Thank you for your reply.

**Comment by dinkypumpkin** [comment]
I should also mention that this issue could arise with regional variants  (NI/Scotland/Wales) of BBC One and BBC Two regardless of whether or not you use Quick Caching, so be on the lookout for those as well.

**Comment by willson556** [comment]
This should be fixed by b34200d59482cd9550be50773fdacef15d6b0afb and a corresponding update to my server.
