### ISSUE TITLE
Search not finding BBC TV Programs,  - ITV and BBC radio are OK

### ISSUE THREAD

**Issue by whitedb** [GetiPlayerAutomator/get-iplayer-automator#487]
Recently the search for seemingly all BBC TV programs has stopped working.  I can force a cache update but when I search for a recent (<7days old) BBC TV program it is not found.  Examples include regulars such as Eastenders, Casualty, Have I got news for you......   ITV programs are found with no problems along with BBC radio programs.  If I go to iplayer and locate the program and then employ the "use current webpage" option I can download a BBC TV program.

I wonder if caching of BBC TV programs seems to have stopped working.  I observed that when I do a cache update, the first "updating program indexes" lasts about 2 seconds whilst the getting info for ITV feeds lasts about 20s.

I am running Yosemite 10.10.3 on a Mac Pro 2008 and version 1.8.5 of Getiplayer Automator.  I cannot get any logs as the option under Window for the Log is greyed out.

**Comment by dinkypumpkin** [comment]
Enable Quick Caching in Preferences.  TV searches no longer work without it due to BBC changes.

**Comment by dinkypumpkin** [comment]
Also see #486 for a potential problem with PVR with Quick Caching enabled.

**Comment by whitedb** [comment]
Thanks getting back to me with that suggestion.  I have now enabled Quick Caching and am now able to see some BBC TV programs, listed under my regional area (Cambridgeshire). However, when I search for "The Game", broadcast on the 3rd of June, it is not seen.  My preferences are as below along with the failed search.  Do you have any other suggestions?
Thanks.

![screen shot 2015-06-07 at 23 11 39](https://cloud.githubusercontent.com/assets/12788281/8026375/ac27c6ac-0d6a-11e5-9403-7c29996af519.png)

![screen shot 2015-06-07 at 23 18 18](https://cloud.githubusercontent.com/assets/12788281/8026391/9149b04c-0d6b-11e5-8122-c869009f1aeb.png)

**Comment by whitedb** [comment]
Strangely, when I search for "The Game" under the PVR manager it is found.  Hope this helps.

![screen shot 2015-06-07 at 23 23 12](https://cloud.githubusercontent.com/assets/12788281/8026413/35d2c3c4-0d6c-11e5-9154-4ea2626785fd.png)

**Comment by dinkypumpkin** [comment]
If you already downloaded the last episode of The Game, it won't by default appear in the main search results.  You can change that in the Advanced tab in preferences, but I don't recommend it.

**Comment by whitedb** [comment]
Yes, that was it, I had already downloaded it. Many thanks for such a quick and helpful answer.

As an aside, is there any reason whey the Log command is greyed out under the Window Menu item (but can be accessed from the button on the main console?

**Comment by dinkypumpkin** [comment]
The disabled Log menu item must be a bug.  Please file it as a separate issue so it can be tracked for next release.

**Comment by whitedb** [comment]
OK will do.  I will experiment a bit first to make sure the problem is repeatable and I have all the info you will need.

**Comment by dinkypumpkin** [comment]
Re-opening to avoid any more duplicates

**Comment by CorrieFan** [comment]
No luck getting ITV in Canada.

**Comment by chaddurham** [comment]
Turning on "Quick caching" in preferences seems to fix the issue for me - at least for all the programmes I'm searching for.

**Comment by jefro108** [comment]
Quick caching doesn't seem to be working today - and it appears to be defaulting to the old method, which means there are no TV programmes in the database!

**Comment by dinkypumpkin** [comment]
Cache file server is dead, again.  See [Snow Leopard notes](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Snow-Leopard-Notes) in wiki for instructions on updating embedded get_iplayer. That will properly (albeit more slowly) update caches if server is dead or Quick Caching is disabled.

**Comment by dinkypumpkin** [comment]
Now tracking this latest mess separately in #494

**Comment by willson556** [comment]
Quick caching server is back up. Crashed in the night but has now been rebooted.

**Comment by dinkypumpkin** [comment]
Should be closed by 1.8.6 release
