### ISSUE TITLE
Downloading "The Enforcers" from ITVPlayer failed

### ISSUE THREAD

**Issue by TheLegendOfMart** [GetiPlayerAutomator/get-iplayer-automator#489]
GiA Version 1.8.5 1735
OS Version: OS X Yosemite 10.10.3

It starts downloading then fails and eventually bails out.

[Logging spew moved here](https://gist.github.com/anonymous/83d4837c14f81a063338)

**Comment by willson556** [comment]
Seems to be working fine for me. Likely a one off issue.
