### ISSUE TITLE
No video downloads currently working from the BBC

### ISSUE THREAD

**Issue by larryy** [GetiPlayerAutomator/get-iplayer-automator#490]
Uh oh.  SD video downloads have been failing for a while, and now HD downloads are failing.  Radio is still working.  I've tried three or four different programs and all have failed much the same way.  Verbose log...  It used to be the case that verbose logs were supposed to be attached rather than inline, but github only seems to allow PNG, GIF, and JPG attachments, so... appended.  This is using a reliable VPN in a configuration that has been working for quite some time now.

[Logging spew moved here](https://gist.github.com/anonymous/f984bf48e2e9cfd9db53)

**Comment by mostlyotter** [comment]
The instructions for putting a verbose log into a gist as text are at https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log

I was just able to download Mock the Week: Series 14 - Episode 1 using a custom proxy in both HD and LoW, although Very High, High and Standard continued to fail.

http://i.imgur.com/ex0iaVJ.png

Using GIA 1.3.7.1 with get_iplayer.pl updated manually to GiP 2.94.

**Comment by larryy** [comment]
And today it's working again.  Must have been a transient problem with the CDN last night.  It was down for at least an hour or two, but with no changes -- not even relaunching GiA or reloading the indexes -- it is working perfectly this morning.  In fact, I think the download went a bit faster than ever before, without a single restart.  Guess I'll close this bug.
