### ISSUE TITLE
Moving GIA to new machine

### ISSUE THREAD

**Issue by jonstott** [GetiPlayerAutomator/get-iplayer-automator#491]
Hi, hopefully this should be quick to answer! I'm moving to a new machine and want to avoid having to manually re-enter all the PVR entries. Where is this stored so that I can copy it over? I'll also need to copy the download history as well.

Thanks!

**Comment by mostlyotter** [comment]
The files should be in /Users/Home/Library/Application Support/Get iPlayer Automator.

You don't say which version of OS X you are running, but if it's 10.10 Yosemite, your Library folder may be hidden. See http://www.dummies.com/how-to/content/the-homelibrary-folder-in-os-x-yosemite.html

**Comment by dinkypumpkin** [comment]
Files you need to copy from `~/Library/Application Support/Get iPlayer Automator` to same directory on new machine: `download_history` and all `.automatorqueue` and `.automator` files. The rest will be re-created when you run GiA on new machine.

**Comment by dinkypumpkin** [comment]
You may need to re-enter some of your settings on the new machine (not sure if they get migrated), so check all your preferences as soon as you run GiA on new machine, before doing any downloads.
