### ISSUE TITLE
No shows found: cache file server is dead

### ISSUE THREAD

**Issue by dinkypumpkin** [GetiPlayerAutomator/get-iplayer-automator#494]
The server (tom-tech.com) that provides cache files containing programme data is dead, again. Until it is revived, if you have Quick Caching selected in preferences you will have no programme data and your searches will fail.  Even if you do not have Quick Caching enabled in preferences, your searches will fail because GiA has not been updated with the latest version of get_iplayer, which is required to retrieve programme data from the BBC (#487).  See the [Snow Leopard notes](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Snow-Leopard-Notes) in wiki for instructions on updating the embedded get_iplayer script. The instructions will work for any version of OS X and GiA. That will properly (albeit more slowly) update cache files when the server is dead or Quick Caching is disabled.

**Comment by willson556** [comment]
Server crashed in the night. Rebooted just now and is up again.
