### ISSUE TITLE
Moving to Windows, Is there a Windows Equivalent?

### ISSUE THREAD

**Issue by DisFanJen** [GetiPlayerAutomator/get-iplayer-automator#500]
I know this isn't an issue but I'm not really sure where else to ask this and my GoogleFu is failing me.

My Macbook Air (13" 2010 Ed) is just getting too long in the tooth for what I'm asking of it so I need to upgrade and my current finances means I unfortunately can't afford Apple prices right now.

So, I'm off to the land of the evil empire again and getting a Windows Netbook.

However I cant find anything that's remotely as good as this app for getting iPlayer & ITV content.

Is there a Windows version?  If not is there any chance of a port? Or failing those, anybody have any recommendation as to a Windows app that does the same job (preferably with a GUI)?

Anyway, thanks for looking at this slightly OT question.

**Comment by chewitt** [comment]
There's the get_iplayer installer for Windows and if you arse about with that you can get the PVR web-GUI running ..but nothing comes close to MacOS and GiA. The cheapest Mac prices are still found in the US (in case anyone you know is headed there in the near future) but the Apple refurb store(s) are also worth a look. If you're headed beyond the EU for vacations; get John Lewis to price match one of the more established online retailers and have them do the tax-refund paperwork. I did that for the 13" PB that this is being typed on, and after the £50 refund fee I got about 25% discount on UK RRP which made it about the same as a US purchase; but with £ and € symbols on the keyboard.
