### ISSUE TITLE
GIA stopped working

### ISSUE THREAD

**Issue by davidqld** [GetiPlayerAutomator/get-iplayer-automator#501]
What steps will reproduce the problem?
Just clicking 'start'

What is the expected output? What do you see instead?
Program to download, problems with proxy

What version of GiA are you using? On what version of OS X?
1.8.6 (1741) OSX 10.10.4

What programme are you attempting to download (full title, series and episode)?
Effects all programs on ITV and BBC

If you cannot download a programme, provide a verbose log of the attempt (see Verbose Log in wiki).
Get iPlayer Automator 1.8.6 Initialized.

Updating Program Index Feeds from Server...
AppController: Index was Up-To-Date.

INFO: Loading proxy settings...
INFO: Custom Proxy: address=[128.199.185.15] length=14
INFO: Proxy load complete.
INFO: Testing proxy (may take up to 30 seconds)...
INFO: Proxy test complete.
INFO: Using proxy: http://128.199.185.15

AppController: Starting Downloads

Downloading Show 1/1:

ITV Download (ID=100142): Downloading Coronation Street - Wed 01 Jul 2015
INFO: Preparing Request for Auth Info
DEBUG: Metadata URL: http://mercury.itv.com/PlaylistService.svc
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 500
DEBUG: Metadata response: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode>s:InvalidGeoRegion</faultcode><faultstring xml:lang="en-GB">The client is in a geographical region that does not have access to the content</faultstring></s:Fault></s:Body></s:Envelope>
ITV Download (ID=100142): ERROR: Access denied to users outside UK.

AppController: Downloads Finished
ITV Download (ID=100142): Download Failed

Please provide any additional information below.
This problem started about 2 weeks ago, using provided proxy gives "proxy could not be retrieved" message and using custom proxy always gives "proxy failed to load test page" message. Failed download solutions "Broadcaster thinks you are outside the UK. Please enable the provided proxy option in preferences"

I also followed the snow leopard work round but made no difference

I am in Australia but not had this problem go on for so long before

Thanks for your help

David

**Comment by chewitt** [comment]
It's a self-evident problem; use a proxy that isn't geo blocked. Close the issue report pls.

**Comment by davidqld** [comment]
How do I find a proxy that is not geo blocked? Never had this problem before. Always worked with supplied or a custom proxy. What happened 2 weeks ago for this to stop working?
