### ISSUE TITLE
hash fragment in URL breaks "use current page"

### ISSUE THREAD

**Issue by dagsuk** [GetiPlayerAutomator/get-iplayer-automator#502]
hi   when i try and use current page to download player radio shows i keep getting this error 

Invalid Page: http://www.bbc.co.uk/programmes/b061qsdr#auto
Please ensure the frontmost browser tab is open to an iPlayer episode page.

i get this on both my macs  one yosemite one el captain     is it a setting i ned to change    any help gratefully recived   :-) 

the player page is the only page opened in safari 

thanks derek

**Comment by dinkypumpkin** [comment]
Remove the "#auto"

**Comment by dagsuk** [comment]
thanks for looking into this :-)     can't remove hash auto :-(    hopefully bug can be fixed   love this program 

cheers again

**Comment by dinkypumpkin** [comment]
Of course you can.  Delete it from the URL in the browser and hit Return to load the page without it.

**Comment by dagsuk** [comment]
cheers never thought of that  works when i do that   thanks again
