### ISSUE TITLE
ITV Incorrect Season

### ISSUE THREAD

**Issue by stickenhoffen** [GetiPlayerAutomator/get-iplayer-automator#503]
Me again, seems the season number is incorrect on (I think) the new bitrate versions.

For example:

```-rw-r--r--@ 1 me  staff  530244836 Jul 15 23:11 Heartbeat.s01e10.Changing Roles.mp4```
```-rw-r--r--@ 1 me  staff  364198874 Jul 15 23:01 Heartbeat.s17e09.The Devil Rides Out.mp4```

The first is the higher bitrate, the second the lower/older bitrate.

**Comment by dinkypumpkin** [comment]
It appears there is no longer a series number in the programme metadata, so it will default to 1.  There is nothing GiA can do about that, unfortunately.

**Comment by stickenhoffen** [comment]
Thanks for checking it out.

**Comment by pstibbons** [comment]
Regarding ITV programs, how do get by the barrier presented asking you to sign up?  Thanks.

**Comment by stickenhoffen** [comment]
Seems now they are duplicating episode numbers! :(

Would it be possible to add a preference to allow GIA to download a file with an identical filename?

  Some Show - s01e01.mp4
  Some Show - s01e01 - 2.mp4

Something like that, perhaps?
