### ISSUE TITLE
Get current webpage fails when url is appended with #play

### ISSUE THREAD

**Issue by joewestcott** [GetiPlayerAutomator/get-iplayer-automator#504]
Sometimes, depending on how you landed on the page the url will be appended by #play, causing GiA to fail parsing the link.
This happens when a user clicks the play button icon inside the programme thumbnail instead of the image or text, such as on this page: http://www.bbc.co.uk/radio1/programmes/schedules

Solution, ignore everything in the url after the hashtag.

**Comment by dinkypumpkin** [comment]
Duplicate of #502
