### ISSUE TITLE
All radio downloads fail

### ISSUE THREAD

**Issue by Cueless** [GetiPlayerAutomator/get-iplayer-automator#505]
What steps will reproduce the problem?
Any attempt to download a BBC radio play
What is the expected output? What do you see instead?
I expect the selected play to download.  I see a window with DOWNLOAD FAILED and a second window titled Failed Download Solutions" opens up.  It says  Problem Unknown.  Please submit a bug report from the application menu

What version of GiA are you using? On what version of OS X? 1.8.6  OS X 10.7.5

What programme are you attempting to download (full title, series and episode)?  MM Kaye The Far Pavilions Omnibus Episode 1

If you cannot download a programme, provide a verbose log of the attempt (see Verbose Log in wiki).

Please provide any additional information below.
I am a pensioner  I know nothing whatsoever about computers and submitting this issue has taken many days of reading and looking up terminology.  I apologise for my lack of understanding.  I only know that Get iPlayer Automater has worked splendidly since November 2014 and one morning it no longer worked.  Any help anyone can offer will be greatly appreciated.  I am in the middle of these plays and am now missing the final sequence.

**Comment by CorrieFan** [comment]
Attempts to download ITV programs from Canada have been failing for more than a week, using both the proxy provided and a custom proxy –– http://149.3.143.250:1080. I'm using the latest version of GIA on the latest Apple computer with the latest software. This is the message I get:

Failed to load http://www.google.com within 30 seconds
Using proxy: http://149.3.143.250:1080
Error: The request timed out

Or is ITV being as vigilant as BBC and preventing GIA from working?

**Comment by dinkypumpkin** [comment]
Without the verbose log information you were instructed to provide, no one will be able even to hazard a guess what is wrong on your machine.

**Comment by mostlyotter** [comment]
The instructions for providing a Verbose Log are at https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log

Cueless, are you in the UK?

Even if you are outside of the UK, you can go to the iPlayer web page for most radio plays and listen using Safari or another browser, just to keep up until you have GiA working again.

If you are outside of the UK, the proxy that GiA provides has not been working for some time.

For radio programmes (but not for television), you could try going to GiA's Preferences and changing the Proxy setting from Provided to None. You should then be able to get audio files with a lower bitrate. The sound quality won't be as good, but will be comparable to listening on the webpage.

**Comment by Cueless** [comment]
It didn't ask for Verbose, Dinkypumpkin.  The instructions said I 'might' be asked for that but when it wasn't in the list of instructions, I decided it best not to second guess it.  

I confirm I am in the UK, Mostlyotter, but I had noticed in the log it said something like 'this may be because you are outside the UK' which puzzled me.  I have just followed your instructions about the proxy and the file has downloaded at last!  It has a funny string in the file name:  MM Kaye - The Far Pavilions Omnibus.s01e01.Episode 1   It doesn't usually have .s01e01.  But it seems to sound just fine.  

Thank you both for helping.  Any suggestions to prevent this happening in future will be greatly appreciated and I apologise profusely for not understanding better.  I feel like I'm always on the outside looking in nowadays.  It's a world where a single 'dot' out of place can bring the house down.  For now, I am hugely relieved.  You've made my day.  And if there's anything else you want me to do, please ask.

**Comment by mostlyotter** [comment]
The custom and provided proxy settings are only for those outside the UK. If you keep None checked, then you should be able to get the full quality audio available for those in the UK (and television programmes too).

If you have further problems, then do try to provide a verbose log. (This is not something that most of us Mac users are familiar with, but the instructions do work.)
