### ISSUE TITLE
Can't download ITV programs

### ISSUE THREAD

**Issue by richdruitt** [GetiPlayerAutomator/get-iplayer-automator#509]
I've been having issues download ITV programs today. 

From the log.
ITV Download (ID=100448): Downloading Hello Campers - Thu 03 Sep 2015
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
INFO: Metadata processed.
INFO: Requesting programme data.
INFO: Program data processed.
INFO: Launching RTMPDUMP...
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
ITV Download (ID=100448): RTMPDUMP finished

That's as far as it gets. It stays at initialising, however it just moves onto the next program. BBC programs seem to be having no problems, just ITV.

**Comment by dinkypumpkin** [comment]
Works fine here. You probably just didn't wait long enough after broadcast for the stream to be available.  Sometimes 2 hours isn't enough.  If that happens, GiA just croaks as you saw.

**Comment by richdruitt** [comment]
I have waited more than 2 hours, I've restarted my computer. I get the same problem over and over again. ITV programs just refuse to download. I'll get all BBC programs without a problem, but ITV, they just start "Initialising", then the RTMPdump launches, then it hangs and failed, giving me a non descriptive error message. "Problem Unkown. Please submit a bug report from the application menu."

I'm sorry I can't be anymore helpful with the information, as I don't really know how the software works. Up until a few days ago, I was having no problems at all.

Any assistance or suggestions would be greatly appreciated. I'm unsure what it is that I'm doing wrong.

**Comment by dinkypumpkin** [comment]
See if this applies to you: https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues/508

**Comment by dinkypumpkin** [comment]
Sorry - forget that last suggestion.  You should get a different error in that case.  See:

https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Reporting-Issues
