### ISSUE TITLE
Downloads Failing Since Sunday

### ISSUE THREAD

**Issue by craigchome** [GetiPlayerAutomator/get-iplayer-automator#511]
Hi,
All downloads are failing with an Application Error and the following log...
I am on MAC OSX 10.10.5 and iPlayer Automator 1.8.6

I am not using a proxy as I am running with a UK ip address. Watching BBC/ITV etc works just fine.

Get iPlayer Automator 1.8.6 Initialized.

Updating Program Index Feeds from Server...
AppController: Index was Up-To-Date.

INFO: Loading proxy settings...
INFO: Loading provided proxy (may take up to 20 seconds)...
INFO: Proxy load complete.
INFO: Testing proxy (may take up to 30 seconds)...
INFO: Proxy test complete.
INFO: Using proxy: http://185.5.64.178:8080

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=435): Downloading Doctor Foster - Episode 1
INFO: Using Proxy http://185.5.64.178:8080
435:	Doctor Foster - Episode 1, BBC One, , default
INFO: 1 Matching Programmes
WARNING: The 'default' programme version could not be determined
WARNING: No programme versions found
WARNING: You may receive this message if you are using get_iplayer outside the UK
BBC Download (ID=435): Doctor Foster - Episode 1 Failed

AppController: Downloads Finished

Can anyone help please?

**Comment by dinkypumpkin** [comment]
Read the output you posted. You most certainly are using a proxy. The "Using proxy..." messages should have given you a clue. See #508.
