### ISSUE TITLE
add support for HLS

### ISSUE THREAD

**Issue by larryy** [GetiPlayerAutomator/get-iplayer-automator#513]
With BBC planning to deprecate RTMP streams in favor of HLS streams, GiA is in danger of being broken at any moment.  Since get_iplayer supports HLS streams already it is at least feasible for GiA to support them, and it would be good to do this before RTMP goes away.

**Comment by JSG15** [comment]
It looks as if this has happened already. GiA has failed all downloads for the past few days. using get_iplayer through terminal all i need to do is change 'mode=best' to 'mode=hlsbest' and it stream/downloads the HD version no problem. so i believe its just a change to the 'tvmode=' responses.

**Comment by dinkypumpkin** [comment]
Nothing has changed yet.  Problems with HD are a separate issue, possibly complicated by being outside the UK (if that applies to you).  Explained here:

https://squarepenguin.co.uk/forums/thread-520-post-2792.html#pid2792

**Comment by larryy** [comment]
FYI, as I understand it...  Two CDNs provide HD RTMP streams: Akamai and Level3.  Akamai has long blocked non-UK access.  Level3 allows it.  And the proxy used by GiA and gip only applies to interactions with the BBC program data sources, not these streams, so all RTMP streaming is subject to location blocking.  Unfortunately, Level3 is having trouble currently.  Which means there are no usable HD RTMP sources outside the UK currently.  As you've discovered, HLS HD *is* available outside the UK still.  That's why your gip solution with hlsbest (I had to switch to hlshd) works, but GiA is not working for you currently.  Hopefully Level3 will be fixed, but there's no saying when that will happen.  Besides gip + HLS, another workaround is a  true VPN solution that shows your IP as being inside the UK; GiA works in this configuration, though more slowly.

It may be worth noting, if GiA supported HLS there would be a workaround for the problem now, which would be much appreciated.  Though I realize that non-UK access is never a priority for GiA.

**Comment by larryy** [comment]
Sorry, I meant to say, GiA works with a full VPN solution specifically because Akamai is still serving HD RTMP streams correctly, but is only available in the UK.

**Comment by dinkypumpkin** [comment]
The BBC have brought in new streams for the iPlayer site, so I suspect those Level3 HD streams are gone for good. No way to know for sure.

**Comment by JSG15** [comment]
Thank you everyone, this clears things up a lot.
