### ISSUE TITLE
GIA has not been working since mid-September 2015

### ISSUE THREAD

**Issue by wjshack** [GetiPlayerAutomator/get-iplayer-automator#514]
I am connecting through a UK VPN. This has worked fine in the past, but I can no longer download from either BBC or ITV. Log says unknown issue. GIA up to date.

**Comment by dinkypumpkin** [comment]
First, read this:

https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Using-GiA-in-the-UK

If you have taken care of that, then it's most likely your VPN has been rumbled. On the off chance you really, truly, absolutely know otherwise, read this:

https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log

And follow those instructions absolutely to the letter.

**Comment by wjshack** [comment]
> On Sep 19, 2015, at 11:01 AM, dinkypumpkin <notifications@github.com> wrote:
> 
> First, read this:
> 
> https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Using-GiA-in-the-UK <https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Using-GiA-in-the-UK>
> If you have taken care of that, then it's most likely your VPN has been rumbled. On the off chance you really, truly, absolutely know otherwise, read this:
> 
> https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log <https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log>
I have addressed the issue of using GIA-in-the-UK. I am not using a proxy when I am logged into my UK VPN. The question is apparently whether my VPN “has been rumbled”. What I do know is that if I log into iPlayer in my browser when connected via the VPN, I can view iPlayer stuff and download it via “BBC iPlayer download”. 

Get_iPlayer and my VPN were working fine for me up until this week. Does it still seem unlikely that my VPN is the problem or should I proceed with 

> https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log <https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log>

**Comment by dinkypumpkin** [comment]
What happens in browser is irrelevant to GiA. Verbose log is only way to get more info, though it may not be definitive in the case of blocked VPN. You would need to run get_iplayer itself for that. But it would provide clues if there is another problem.
