### ISSUE TITLE
HTML5 iPlayer support

### ISSUE THREAD

**Issue by madranet** [GetiPlayerAutomator/get-iplayer-automator#515]
Any thoughts on if/when this will be added?

As I'm sure you'll know, Auntie has just announced that iPlayer is now available in beta 'sans-Flash':

[BBC HTM5 iPlayer Info Page](http://www.bbc.co.uk/html5)

Great app, by the way!

**Comment by dinkypumpkin** [comment]
That is irrelevant to GiA. HTML 5 is only relevant to web browsers, and MPEG-DASH isn't a good format for for GiA.  And iPlayer has had non-Flash streams for a long time.  See #513.
