### ISSUE TITLE
WARNING: The 'default' programme version could not be determined WARNING: No programme versions found

### ISSUE THREAD

**Issue by ddasterdly** [GetiPlayerAutomator/get-iplayer-automator#516]
INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=667): Downloading Have I Got a Bit More News for You: Series 50 - Episode 1
INFO: encodinglocale = UTF-8
INFO: encodinglocalefs = UTF-8
INFO: encodingconsoleout = UTF-8
INFO: encodingconsolein = UTF-8
INFO: ${^UNICODE} = 39
INFO: User prefs dir: /Users/gmills/Library/Application Support/Get iPlayer Automator
INFO: System options dir: /etc/get_iplayer/options
	versionlist = default
INFO: Search args: '667'
INFO: Additionally getting cached programme data for tv
INFO: Got 1749 file cache entries for tv
667:	Have I Got a Bit More News for You: Series 50 - Episode 1, BBC One, , default
INFO: 1 Matching Programmes
INFO: Loaded history for first check.
INFO: Loading recordings history
INFO: Programme not in history
INFO: Programme metadata URL = http://www.bbc.co.uk/programmes/b06h8yzt.xml
INFO: Getting page http://www.bbc.co.uk/programmes/b06h8yzt.xml
INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/b06h8yyh/proto/rtmp?cb=88196
INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/b06h8yyh/proto/rtmp?cb=16736
INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/b06h8yyh/proto/http?cb=99586
INFO: No streams available for 'original' version (b06h8yyh) - skipping RDF
INFO: No streams available for 'original' version (b06h8yyh) - deleting
WARNING: The 'default' programme version could not be determined
WARNING: No programme versions found
![screen shot 2015-10-07 at 1 06 34 pm](https://cloud.githubusercontent.com/assets/15018722/10344958/46a40fd6-6cf4-11e5-85f1-77fc7e7d6473.png)

WARNING: You may receive this message if you are using get_iplayer outside the UK
ERROR: Could not get programme metadata
BBC Download (ID=667): Have I Got a Bit More News for You: Series 50 - Episode 1 Failed

AppController: Downloads Finished

**Comment by dinkypumpkin** [comment]
So, are you outside the UK?  If so, unless this was a temporary server glitch, it probably means your VPN has been rumbled.  If you're in the UK, try again later.  Works fine here.

**Comment by ddasterdly** [comment]
Yes greed. Thanks for verifying. doing a curl request on the http strings yields the dreaded. geoip error.

Thanks again.
