### ISSUE TITLE
Incomplete list of available ITV programmes

### ISSUE THREAD

**Issue by sheepworrier** [GetiPlayerAutomator/get-iplayer-automator#523]
I've tried with Quick Caching enabled / disabled, but still only shows one entry (episode 4) for "Ladies of London" in itv.cache.  However, there have been 2 episodes on the ITV Player website since 11th November:

https://www.itv.com/itvplayer/ladies-of-london/series-2/

**Comment by dinkypumpkin** [comment]
That page only shows one episode since 11 Nov.  Regardless of that, if you don't see an episode in search results, just use the "Use Current Webpage" function.

**Comment by sheepworrier** [comment]
Sorry, I meant there are two episodes on the webpage, but only one in itv.cache.

I did not know about the "Use Current Webpage" button - a great feature!

**Comment by IMRot** [comment]
Use current webpage doesnt work either

**Comment by erikmh** [comment]
I see this problem with many ITV titles. Today, for example, [Lewis](http://www.itv.com/hub/lewis/1a5634a0022) shows 11 episodes available in the new ITV hub. The same 11 episodes are visible in a recently refreshed itv.cache file <~/Library/Application Support/Get iPlayer Automator/itv.cache>. However, within the GiA search results table, searching for `Lewis` shows only six Lewis episodes. It’s almost as if the search were drawing from some source other than the itv.cache file.

I have tried not only the “Force Cache Update” command, but also deleting the cache and re-creating it with a “Check for Cache Update.” Nothing I do will give me the full list within the GiA interface.

**Comment by dinkypumpkin** [comment]
Cannot reproduce.  All (now) 12 episodes of Lewis, all 21 episodes of Heartbeat, etc., appear in search results. If you have already recorded some episodes of Lewis, those episodes won't appear in the search results unless you select the "Include downloaded shows in search results" in the Advanced tab in preferences.

**Comment by erikmh** [comment]
You called it. I don’t know about sheepworrier, but for me it was exactly the previously downloaded episodes that were missing. Sorry for the time-waster.

**Comment by IMRot** [comment]
What do you mean by all that. The missing programmes are all the new ones.
