### ISSUE TITLE
Cannot download past shows

### ISSUE THREAD

**Issue by pavlovich** [GetiPlayerAutomator/get-iplayer-automator#524]
I'm trying to download 3 episodes of a given show. I am hooked up via VPN. It downloaded today's episode without error. The past ones are failing. Here is the log:

Get iPlayer Automator 1.8.6 Initialized.

Updating Program Index Feeds from Server...
AppController: Index was Up-To-Date.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/3:

BBC Download (ID=395): Downloading EastEnders - 09/11/2015
395:	EastEnders - 09/11/2015, BBC One, , default
INFO: 1 Matching Programmes
WARNING: The 'default' programme version could not be determined
WARNING: No programme versions found
WARNING: You may receive this message if you are using get_iplayer outside the UK
BBC Download (ID=395): EastEnders - 09/11/2015 Failed

Downloading Show 2/3:

BBC Download (ID=396): Downloading EastEnders - 10/11/2015
396:	EastEnders - 10/11/2015, BBC One, , default
INFO: 1 Matching Programmes
WARNING: The 'default' programme version could not be determined
WARNING: No programme versions found
WARNING: You may receive this message if you are using get_iplayer outside the UK
BBC Download (ID=396): EastEnders - 10/11/2015 Failed

Downloading Show 3/3:

BBC Download (ID=397): Downloading EastEnders - 12/11/2015
397:	EastEnders - 12/11/2015, BBC One, , default
INFO: 1 Matching Programmes
WARNING: The 'default' programme version could not be determined
WARNING: No programme versions found
WARNING: You may receive this message if you are using get_iplayer outside the UK
BBC Download (ID=397): EastEnders - 12/11/2015 Failed

AppController: Downloads Finished

**Comment by mtcp56** [comment]
Did you ever resolve this issue?  This sometimes happens to me when I'm using Astrill's OpenWeb proxy rather than the actual VPN (Stealth or OpenVPN).  Make sure that "send all traffic" is checked if you're using Mac Preferences to connect to your VPN.

**Comment by dinkypumpkin** [comment]
Cannot reproduce. There is nothing GiA can do about proxy/VPN problems, anyway.
