### ISSUE TITLE
ITV site restructuring: cannot now “Use Current Webpage”

### ISSUE THREAD

**Issue by erikmh** [GetiPlayerAutomator/get-iplayer-automator#525]
ITV seems to have restructured everything, including invalidating its previous “canonical URLs” and replacing them with new ones, *à la* <http://www.itv.com/hub/lewis/1a5634a0021>.

Though prettier, episode titles are now completely lacking (they’re not even hidden), and GiA, unsurprisingly, tells me that the pages are “Invalid.”

I have not found any work-around to get to the “old” site. Am I missing something obvious, or are we essentially dead in the water with ITV for now?

**Comment by IMRot** [comment]
It started working again now its stopped again

**Comment by pmhird** [comment]
Definitely something weird here, if you look at long running series, the latest episodes are cached correctly, but the series is not continuous. Take X-Factor for instance, yes I know cr@p TV, but episode 21 and 22 are missing, and 25 and 26 are missing. But 27 and 28 are there. The PIDs are continuous with no gaps, so its like 21,22,25 and 26 don't exist, yet they can be played from the ITV website. Trying to grab a PID from "current webpage" doesn't seem to work with the new itvplayer/itvhub URL... Is there any way to manually find the PID from the page source?

**Comment by IMRot** [comment]
Thanks for the reply, its working again now but the BBC still doesn't work at all.
RegardsIan 


    On Monday, 14 December 2015, 16:22, pmhird <notifications@github.com> wrote:
 

 Definitely something weird here, if you look at long running series, the latest episodes are cached correctly, but the series is not continuous. Take X-Factor for instance, yes I know cr@p TV, but episode 21 and 22 are missing, and 25 and 26 are missing. But 27 and 28 are there. The PIDs are continuous with no gaps, so its like 21,22,25 and 26 don't exist, yet they can be played from the ITV website. Trying to grab a PID from "current webpage" doesn't seem to work with the new itvplayer/itvhub URL... Is there any way to manually find the PID from the page source? —

**Comment by pmhird** [comment]
Well I still can’t use current webpage on ITV… using 1.8.6 on OSX 10.9.5. My “use current webpage” feature works just fine on BBC ones, just not on ITV…

**Comment by dinkypumpkin** [comment]
To be clear on this:

 "Use Current Webpage" will not work with ITV until GiA has been patched.  There is no workaround.

Any missing episodes (e.g., X Factor) are simply not present in the ITV data feed. This happens from time to time and there is nothing GiA can do about it.  

You can't get PIDs from the ITV page source. There is a more laborious way to find them, but they are useless without corresponding cache entries, so no good for missing episodes.

**Comment by user182015** [comment]
Yes, the 'Use Current Webpage' doesn't work on ITV. All episodes are on ITV Hub; they just don't appear in GiA search results. I have had this problem too and I really need to download a TV Show which becomes unavailable in 3 days.

**Comment by erikmh** [comment]
@user182015: The problems you’re seeing are unrelated:

1. The “Use Current Webpage” (which I’d originally posted about), as explained by @dinkypumpkin, will not work until GiA is modified to handle the ITV Hub’s radically new format.

2. As far as the search results are concerned, the feeds of available recordings that GiA (and other clients) rely on doesn’t always exactly match reality — and, as he’s said, there’s nothing that can be done about that; however,
  
   a. On another thread, @dinkypumpkin reminded me to check the setting “Include Downloaded Shows in Search Results” in the Advanced tab of Preferences. In my case, it was *not* checked (which is usually what one wants) — but I had previously downloaded (and deleted) low bitrate versions of a few shows and (naturally) GiA wasn’t showing them in the search results. You might want to toggle that tickbox and see if that helps you.

  b. You can also try looking at `~/Library/Application Support/Get iPlayer Automator/itv.cache` to double-check whether your episode was in ITV’s data feed.

  c. I suppose there’s always the outside chance that your cache could be corrupted, although I’ve never seen any indication that this is an issue. You could try quitting GiA, deleting the cache file I mentioned above, and then build a new cache (automatically or with “Check for Cache Update.“ But I assume that’s exactly what “Force Cache Update” does, which I bet you’ve already tried.

Good luck!

**Comment by pmhird** [comment]
Thanks for all that, I'll give it a go.

**Comment by pmhird** [comment]
I checked library/application support and the missing episodes are not in the itv.cache either, moreover the cache numbers are consecutive so none are missing or corrupted. Very odd.

My understanding is that only shows from the last seven days are now cached, so wouldn’t deleting itv.cache and re-building it actually reduce the number of shows available to download from my current position?

PH

**Comment by dinkypumpkin** [comment]
Limit doesn't apply for ITV. GiA caches whatever is in their data feed.

**Comment by erikmh** [comment]
> I checked library/application support and the missing episodes are not in the itv.cache

Ah, then it sounds like your show is a victim of the (usually small) discrepancy between ITV’s data feeds and what they show as available on-line. I think you’re out of luck until such time as GiA’s “Use Current Web Page“ supports the new format.

> My understanding is that only shows from the last seven days are now cached, so wouldn’t deleting itv.cache and re-building it actually reduce the number of shows available to download from my current position?

Not for ITV. I haven’t experimented much with the BBC cache, but I think the seven-day limit does apply there.

**Comment by pmhird** [comment]
You might be right-the delete and rebuild of itv.cache didn’t solve it… still shows missing. Its not a date thing either as itv shows from the missing dates but from other series are there.

Oh well..

**Comment by user182015** [comment]
Is there an update in the works for to support the Use Current Webpage on the new ITV Hub?

**Comment by SimonRepton** [comment]
Would also love to see an update for this issue.  Thanks!

**Comment by erikmh** [comment]
This looks like excellent news indeed, dinkypumpkin. Many thanks for the fix!

I’m comparatively new around here, though — is there something I should do in order to see this as an update from within GiA? It currently tells me that what I have (1.8.6 r1741) is the most recent version.

**Comment by dinkypumpkin** [comment]
Fix won't be generally available until next release. No, I don't know when that will be.

**Comment by IMRot** [comment]
when I try to download prpgrams from any station it says format not supported. Any ideas 

Regards

**Comment by makpufterpup** [comment]
Glad to see that this has been fixed, but when I download the latest release it still gives the error message.

**Comment by IMRot** [comment]
It seams to be the proxy that isn't working, it hasn't worked for months 

    On Thursday, 14 January 2016, 4:43, makpufterpup <notifications@github.com> wrote:
 

 Glad to see that this has been fixed, but when I download the latest release it still gives the error message.—

**Comment by erikmh** [comment]
Is there anything I can do as a mere user (with XCode, and lots of development experience from the ’70s through the early ’00s — but nothing recent) to help @dinkypumpkin's fix along into an actual update?

I vastly prefer the “Use Current Webpage” workflow anyway, but combined with the 5% – 10% error rate with ITV’s PID data feeds, it means that a lot of ITV programming is currently completely unavailable.

**Comment by willson556** [comment]
Sorry for the delay everyone. I'll get a release out today or tomorrow.

**Comment by jefro108** [comment]
Any news on the latest release? It'd be great to be able to add ITV programmes from the web page :)

**Comment by dinkypumpkin** [comment]
No, but there is a pre-release build available. See wiki for info.

**Comment by jefro108** [comment]
That's great. I'd forgotten about pre-release builds being available. Thanks :)

**Comment by wdavies39** [comment]
Thanks to Dinkypumpkin for a prompt response, and apologies for not reading all the prior posts. The "Use Current Webpage" button does work for ITV programmes on the pre-release version 1.8.7 pre2.  Great news - I've got ITV back!!
