### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by elflife** [GetiPlayerAutomator/get-iplayer-automator#530]
What steps will reproduce the problem?

What is the expected output? What do you see instead?

**What version of GiA are you using? On what version of OS X?**
Version 1.8.6 (1741)
**What programme are you attempting to download (full title, series and episode)?**
Book of the Week, Empress Dowager Cixi: The Concubine Who Launched Modern China, 
Episode 1 of 5
*http://www.bbc.co.uk/programmes/b03bdbpw*
**If you cannot download a programme, provide a verbose log of the attempt (see Verbose Log in wiki).**
[verbose log.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/58883/verbose.log.txt)
**Please provide any additional information below.**
I can listen to the whole program on a browser without VPN. But can't download it.
When I click "Use Current Page", the "Show Name - Episode Name" content shows up in full on the Download Queue, but after clicking "Process PID", the "Show Name - Episode Name" column became "Unknown: PID Not Found"

**Comment by dinkypumpkin** [comment]
Cannot reproduce. Your log indicates that you couldn't connect to the BBC servers to download programme metadata. There may have been a server glitch, or just some problem with your upstream network, or maybe your VPN was at fault. Whatever the cause, it is outside GiA's control. Also, being able to play a programme in the browser doesn't necessarily mean that GiA can download it. All I can tell you is to try again later.

**Comment by elflife** [comment]
Thanks!
