### ISSUE TITLE
BBC killed get_iplayer (again) - GiA cannot search for or download BBC programmes

### ISSUE THREAD

**Issue by whitedb** [GetiPlayerAutomator/get-iplayer-automator#534]
I was looking for the Show "Eve" on CBBC.  It was not found in the search in Get-iPlayer-Automator.  So I loaded the iPlayer webpage, found the show and then applied the "Use Current Webpage" to load it into the queue.  It appears with the PID I can see in the open webpage and the correct tittle.  The show plays in the safari webpage.

When I hit start in Get-iPlayer-Automator there is a delay of several seconds, the application beach balls and then I see Beginning, then Initializing flash past and then the download fails with a message: 

"The show could not be located on iPlayer/ITV player.  If outside the UK, use a proxy"

In the Get-iPlayer-Automator window the pid remains but the status is now not available and under showname it now says "Unknown: PID not found"
 
I am in the UK.  Note that iPlayer had a trailer before the show when viewing on the webpage.
I had no problem loading this show last week.

**Comment by gacres2** [comment]
This is happening to me too - it seems the BBC are doing maintenance on some key pages. All BBC radio and TV seems to be affected, but ITV is not (for me at least). It isn't clear to me if it is temporary or long-term maintenance.

**Comment by tparis0022** [comment]
I'd like to echo this issue. A week or so ago, I was able to download shows perfectly fine but now getting issues. I suspect the BBC are blocking downloads..

I'm using a MacBook Pro and an iMac, both fully up to date in OS, Chrome and Safari browser plus your application is fully up to date. However, on both MacBook Pro and iMac, the application is crashing when the application starts, I believe during the caching process and becoming unresponsive often. The search function cannot locate any shows so I fired up Chrome and pressed Play on the selected show, it worked and played no problem in browser. However, when clicking on 'Use Current Webpage', the video is added to the download section. When I click 'Process PID', the application tends to thinking a little bit then responds with the status changing to 'Not Available' and the Show Name - Episode Name changing to 'Unknown: PID Not Found'.

Failed Download Solutions states the Show Name as Unknown: PID Not Found and the Diagnosis says 'The show could not be located on iPlayer/ ITV Player. If outside the UK, use a proxy'. Out of interest, last week in Denmark, I did try through Hola VPN proxy and it didn't work. Tonight, I've also tried turning off ITV TV and BBC TV items to cache within the application settings, both have no effect towards a positive conclusion.

I sincerely hope a solution to this issue can be found quickly and easily as I really would love to download these episodes! If I can help any further, please let me know and I'll be happy to help

**Comment by dinkypumpkin** [comment]
https://squarepenguin.co.uk/forums/thread-623-post-3392.html#pid3392

**Comment by robincm** [comment]
0930 BST - BBC programmes suddenly available again! Wonder if this is just a blip!

Thanks dinkypumpkin for all your hard work.

**Comment by 4x700** [comment]
A forum member on squarepenguin.co.uk called wr8112 has managed to fix the the problem with PID's not being found in the windows based version of get_iplayer. Is there a way to port over the get_iplayer.cgi and get_iplayer.pl from the windows version of get_iplayer to get_iplayer automator?

Post Number 34 
https://squarepenguin.co.uk/forums/thread-623-post-3417.html#pid3417

**Comment by mostlyotter** [comment]
I have the development version of get-iplayer working for radio in GiA using a PID, but you'll need to use Terminal and to change package contents.

You may also need to change settings, depending on your version of OS X, so that you can see hidden folders.

First, zip (or otherwise backup) the following to save them in zipped form: the GIA application and the GIA folder in Home > Library > Application Support.

Go to https://github.com/get-iplayer/get_iplayer/wiki/gipdev

Copy the command under "Direct download 1.Download the Git HEAD version to working directory CLI" and paste into Terminal. Hit return.

That should download a file named get_iplayer to your Home folder. Add the extension .pl to the file.

Control click on the GIA application and select Show Package Contents. Replace the get_iplayer.pl which is in Contents > Resources.

Close GIA, then reopen and see if it works. If not, you have your zipped backup and can wait for an update

(Haven't tried TV yet.)

**Comment by mostlyotter** [comment]
I should add that I have Quick Caching UNchecked in GiA's Preferences.

**Comment by dinkypumpkin** [comment]
Normal service has been restored for now - there is no need to switch to the development version of get_iplayer.  GiA should now be working normally.

**Comment by barneycouch** [comment]
I'm having this problem repeatedly, again, with the "Storyville" episodes, and with some others too. Any news? My location and situation are the same as the OP

**Comment by JJGodden** [comment]
I am having the exact same issue as the OP with all BBC radio shows I'm attempting to download. My location is also the same.
