### ISSUE TITLE
iPlayer indexing seems empty

### ISSUE THREAD

**Issue by pstibbons** [GetiPlayerAutomator/get-iplayer-automator#535]
When l search iPlayer, the only results I get are from itv and radio.  Nothing from iPlayer.  This happened somethings in the past day.  I have a vpn that has been reliable so far.  My method is to download content.  It is possible to see tv and such without downloading content.  But that is not preferred.  Please advise.  Thanks.

**Comment by mtcp56** [comment]
See #534
