### ISSUE TITLE
New BBC3 programmes not appearing in search

### ISSUE THREAD

**Issue by jefro108** [GetiPlayerAutomator/get-iplayer-automator#539]
For example Cuckoo S03E01 is being advertised as new on the new online only BBC3 iPlayer channel, but when I search for Cuckoo only the series 2 episodes appear. 

However if I go to the webpage of the programme http://www.bbc.co.uk/iplayer/episode/p03j1tv9/cuckoo-series-3-1-birth and add it with 'Use current webpage' it is added to the download queue and will download ok.

This of course means that the programmes, which appear to be being released sequentially and not in one batch, aren't picked up by the PVR, and will involve rechecking when the programme is available, but without an obvious schedule to refer to!

**Comment by dinkypumpkin** [comment]
Web-only programmes have never been indexed by get_iplayer, and thus never available in GiA search results.  That now includes all new BBC Three programmes

**Comment by jefro108** [comment]
Any chance that now that one of the BBC channels is Web-only that get_iplayer will index the BBC3 programmes?

**Comment by dinkypumpkin** [comment]
Not likely

**Comment by jefro108** [comment]
Is that because the BBC aren't providing any information about these programmes that could be indexed by get_iplayer?
