### ISSUE TITLE
Unable to download and ITV programs since last OS X update

### ISSUE THREAD

**Issue by Grimfool** [GetiPlayerAutomator/get-iplayer-automator#543]
Since I updated to OS X 10.11.4 I am unable to download any ITV programs  please see log

Get iPlayer Automator 1.8.6 Initialized.

Updating Program Index Feeds from Server...
    Retrieving tv index feeds.
    Retrieving itv index feeds.
AppController: Index Updated.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/2:

ITV Download (ID=100307): Downloading Doctor Thorne - Episode 3
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
INFO: Metadata processed.
INFO: Requesting programme data.
INFO: Program data processed.
ERROR: Destination file already exists.

Downloading Show 2/2:

ITV Download (ID=100403): Downloading Grantchester - Wed 23 Mar 2016
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
INFO: Metadata processed.
INFO: Requesting programme data.
INFO: Program data processed.
ERROR: Destination file already exists.

AppController: Downloads Finished

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/2:

ITV Download (ID=100307): Downloading Doctor Thorne - Episode 3
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
INFO: Metadata processed.
INFO: Requesting programme data.
INFO: Program data processed.
ERROR: Destination file already exists.

Downloading Show 2/2:

ITV Download (ID=100403): Downloading Grantchester - Episode 4
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
INFO: Metadata processed.
INFO: Requesting programme data.
INFO: Program data processed.
ERROR: Destination file already exists.

AppController: Downloads Finished

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/3:

ITV Download (ID=100307): Downloading Doctor Thorne - Episode 3
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
INFO: Metadata processed.
INFO: Requesting programme data.
INFO: Program data processed.
ERROR: Destination file already exists.

Downloading Show 2/3:

ITV Download (ID=100403): Downloading Grantchester - Episode 4
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
INFO: Metadata processed.
INFO: Requesting programme data.
INFO: Program data processed.
ERROR: Destination file already exists.

Downloading Show 3/3:

ITV Download (ID=101003): Downloading The Only Way Is Essex - Wed 23 Mar 2016
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
INFO: Metadata processed.
INFO: Requesting programme data.
INFO: Program data processed.
INFO: Launching RTMPDUMP...
RTMPDump v2.4-77-gdc76f0a
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
WARNING: HandShake: Type mismatch: client sent 6, server answered 8
INFO: Connected...
ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!
ERROR: HandleInvoke, error decoding invoke packet
ITV Download (ID=101003): RTMPDUMP finished

AppController: Downloads Finished

**Comment by dinkypumpkin** [comment]
"ERROR: Destination file already exists." should be an obvious signal to delete any previous download and try again. "ERROR: DECODING ERROR, IGNORING BYTES UNTIL NEXT KNOWN PATTERN!" signifies poor upstream connectivity or server problems, so try again later - there is nothing GiA can do about that.
