### ISSUE TITLE
How to exclude shows from series-link?

### ISSUE THREAD

**Issue by approtech** [GetiPlayerAutomator/get-iplayer-automator#545]
I have the BBC series 'Click' set to auto-record. Recently they added an edited version of each episode called 'Click - Short Edition' which gets downloaded too. Is there a way to exclude this version while still getting the full one?

**Comment by dinkypumpkin** [comment]
After you have put Click into your series-link list, click show name and change it from "Click" to "Click$". The "$" is a regular expression metacharacter which forces a match at the end of the programme name. If you don't know what a regular expression is, Google is your friend.

**Comment by approtech** [comment]
Excellent, thanks. I'm familiar with regex; just didn't know we could use them in the series-link list!
