### ISSUE TITLE
ITV search no longer works - feeds no longer updating

### ISSUE THREAD

**Issue by GarthRanzz** [GetiPlayerAutomator/get-iplayer-automator#547]
As of yesterday, 4.4.2016, the iTV feed is no longer updating. Even opening an episode to use the Use Current Webpage function doesn't work. BBC streams work just fine and the feed updates when a cache update is performed. It is just the iTV feed not working. Is anyone else experiencing this?

**Comment by GarthRanzz** [comment]
After checking closed issues it seems this may be the case with iTV for now but it looks more like it is different since I was working fine until yesterday. But the pre-release build lets you use the Use Current Webpage so that has solved my problem for now. Would just rather run a cache update though since I grab so many different shows.

**Comment by edjonesy** [comment]
I'm finding this too, player had stopped working but is back again as of yesterday afternoon. How do I go about getting the pre-release version so I can still download itv shows, is it possible?
thanks

**Comment by mostlyotter** [comment]
With 1.8.6 on 10.10.5, the ITV cache seems to have stopped updating after Sunday night, 04 April.

**Comment by dinkypumpkin** [comment]
The GiA cache is updating, but the programme data hasn't been updated at the ITV end since Monday morning (5 Apr). There is nothing GiA can do about that. It's too soon to tell if this is a permanent condition. In the meantime, you should still be able to download single episodes with the pre-release build.

**Comment by edjonesy** [comment]
OK, thanks dinky pumpkin, flipping ITV, how do we download the pre-release version please?

**Comment by edjonesy** [comment]
Found it, working great downloading itv via 'use current webpage', thank you.

Running on a Mac Pro 1.1 running OSX 10.7.5

**Comment by edjonesy** [comment]
Hi Grimfool, at the top of this page, where you have issues selected, theres another tab for 'wiki', select that, prerelease is listed in a panel on the right hand side of that page.

Heres a url too: https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Pre-Release-Builds

It took me a while to find it too.

**Comment by Grimfool** [comment]
Thanks

**Comment by flaxton** [comment]
OK, I downloaded the latest Pre-Release 1.8.7-pre.2 dated 2016-03-17. It still is missing epsides since 4/1. For example, those are the last Coronation Street episodes on ITV, in Get iPlayer.

However, "Use Current Webpage" does work now. Thanks!

Here's hoping the episode listing can be fixed.

**Comment by UbiGit** [comment]
Hi, I downloaded the pre-release but I'm not sure what I have to do to get any ITV drama episodes. I loaded the ITV hub page for the 2nd episode of "The Durrells" then searched for and added "Durrells" to GiP Auto Search results, Only the first episode was returned in the Search Result field with a number (The Durrells - 357021") then I clicked "Use Current Webpage" and nothing was added to the download queue. I just got a Dialogue message which reads "**Invalid Page: http://www.itv.com/hub/the-durrells/2a4156a0002** .... Please ensure the frontmost browser tab is open to an ITV Hub episode page." Safari has the player web page open (in the "Invalid Page"and the episode runs in it, but GiP Auto is not nabbing it...

Any help/pointers appreciated. Ta.

**Comment by edjonesy** [comment]
that's strange, I've just tried that exact page, from your link, it works on my mac pro running 10.7.5 and my work mac pro running 10.11.4, both macs are running the pre-release version. 

I'm sorry I can't help, but at least it narrows it down to something specific to your machine, sadly!

**Comment by dinkypumpkin** [comment]
@UbiGit: you are most likely not actually running the pre-release build. Check "About Get iPlayer Automator" in the menu.

**Comment by Grimfool** [comment]
Hi all,
I get the same as GitHub on my Macbook Pro. I downloaded it here in the UK when we arrived from the US on Monday and consequently am unable to download ITV. The version I downloaded was Version 1.8.7-pre.2 (1753). I downloaded the prerelease to my mac mini in the US last week and that works perfectly when I pull up the program page on the ITV hub
Regards,
Bill

**Comment by dinkypumpkin** [comment]
I can only tell you what I told the other poster: Make sure the version you downloaded is the version you're running. It works fine here with both Safari and Chrome.

**Comment by dinkypumpkin** [comment]
I'm locking this thread to prevent more hijacking. Feel free to repost ITV "Use Current Webpage" issues in a new thread.

**Comment by dinkypumpkin** [comment]
It has been 2 weeks now, so we can probably conclude that ITV has permanently stopped updating the programme data used by GiA. If that remains the case, expect ITV searching to be removed in the next release. I suggest deselecting "ITV TV" in preferences anyway since ITV search results are becoming less reliable each day.

**Comment by dinkypumpkin** [comment]
@UbiGit or @Grimfool: If you are still having "Use Current Webpage" troubles and want to open a new ticket, a suggestion: Save the HTML source of an offending page in a .txt (plain text) file and post it as an attachment to your ticket. Don't paste it into the body of your post, but do post the associated ITV Hub URL. This is unlikely to reveal the actual culprit, but there may be some clues that are only present on your machine.

**Comment by dinkypumpkin** [comment]
Closed by 091cbacdbf9a3ee08588c8365d110a11552674bd
