### ISSUE TITLE
Iplayer automator not initialising

### ISSUE THREAD

**Issue by trackside** [GetiPlayerAutomator/get-iplayer-automator#549]
I am having problems getting i player automator to initialize with any BBC and ITV programs. They can be selected from the search menu and added to the download section however when you hit go they do not initialize and they then time out

**Comment by Hal55** [comment]
I am experiencing the exact same problem as described by 'trackside'.

**Comment by dinkypumpkin** [comment]
Neither of you have provided any useful information for diagnosis. Start with the Reporting Issues page in the wiki, paying special attention to the instruction for creating a verbose log, and try again.
