### ISSUE TITLE
PVR issues

### ISSUE THREAD

**Issue by PhgSpa** [GetiPlayerAutomator/get-iplayer-automator#550]
PVR now selects multiple instances of each item, instead of ignoring ones already downloaded. For example, the BBC Radio 3 Lunchtime Concert PID 12303 appears in the download list about a dozen times, marked "available", despite having been downloaded already.

**Comment by dinkypumpkin** [comment]
Cannot reproduce. Ensure you are using the latest version (1.8.6). Also ensure the previous download is in fact in your history file (File -> Edit Download History). If not, select one of the entries in queue and click "Permanently Skip Select Series-Link Entries" to put it there, then clear queue and try series-link update again. And in the future, provide the full episode title for a troublesome programme. Although 12303 is labelled as PID, it actually isn't, so unfortunately isn't very useful.
