### ISSUE TITLE
"Invalid Page" error on "Get current webpage"

### ISSUE THREAD

**Issue by markuswinter** [GetiPlayerAutomator/get-iplayer-automator#551]
Using Version 1.8.7-pre.2 (1753) from currently Germany via VPN CyberGhost

As the ITV Index feeds do not update I go to the ITV site, log in, go to "The Sweeney", start playing it (plays fine) and try to download it via "Get current webpage". As others already reported I get a

"Invalid Page: http://www.itv.com/hub/the-sweeney/672979"

Tried with both Safari and FireFox (latest version) on MacOS X 10.11.4

Any ideas on what I can do to get it to work?

P.S. Might be useful if one could enter the webpage somewhere …

**Comment by dinkypumpkin** [comment]
Firefox is not supported, and hasn't been for years. Your example works fine here with both Safari and Chrome. Ensure you are actually running the 1.8.7-pre.2 build you downloaded. It seems a bit unlikely that your VPN is causing the problem, but only you can assess what your VPN is doing.
