### ISSUE TITLE
iPlayer not Initialising Downloads

### ISSUE THREAD

**Issue by eustegia** [GetiPlayerAutomator/get-iplayer-automator#554]
Hello,
The downloads aren't initialising. The files update and show ready to download, but when I click the start button, nothing happens. After a short interval, a dialogue box with the following info appears:

"Proxy failed to load test page. Downloads may fail. Do you want to continue?
Failed to load http://www.google.com within 30 seconds.
Using proxy: http://195.99.254.85:3128
Error: The request timed out

If I click "yes" the dialogue goes away, but the download doesn't initialise.

Thanks

![screen shot 2016-04-18 at 4 16 46 pm](https://cloud.githubusercontent.com/assets/18533237/14607365/85ebd9dc-0581-11e6-8ed3-e46fe4d0ed4d.png)
![screen shot 2016-04-18 at 4 17 05 pm](https://cloud.githubusercontent.com/assets/18533237/14607369/88e58070-0581-11e6-9c7b-718c0324c61a.png)

**Comment by dinkypumpkin** [comment]
The error message says it all - the proxy server fails a test, so even if you click Yes to continue it is unlikely to work for downloading. There is nothing GiA can do about that. If you are in the UK, see the project wiki (link above) for info on how to prevent that error. If you are not in the UK, you will have to find better proxy/VPN arrangements.
