### ISSUE TITLE
Unknown error with at least one BBC show

### ISSUE THREAD

**Issue by c00k1e181992** [GetiPlayerAutomator/get-iplayer-automator#556]
Hi there,

Just a quick report that at least on show on iPlayer (or at least the latest episode in the show) is not downloading and throws out an unknown error. 

The show is I Want My Wife Back episode 3 link: http://www.bbc.co.uk/iplayer/episode/b079wqt0/i-want-my-wife-back-episode-3 
I have downloaded the previous 2 episodes but for some reason this episode will not work (non-HD formats do download though so i'm guessing the issue is with the HD format). I don't know if iPlayer is changing their format or if they are adding encryption to shows now but I thought I would report and see if anyone else had had similar issues with any shows.

The download log is posted here: http://pastie.org/private/gkh77eg7wtm9xkklgsxjca
Also I have attached the error thrown out by the attempted download
<img width="802" alt="screen shot 2016-05-05 at 10 17 56 am" src="https://cloud.githubusercontent.com/assets/2762837/15040206/ba54da62-12aa-11e6-9ab3-ab3f203dff28.png">

**Comment by dinkypumpkin** [comment]
Thanks for the log. As you surmised, this appears to be a problem only with the HD version of that programme. It sometimes happens that the HD version isn't available in all formats when a programme is posted to iPlayer, yet there is still metadata pointing to the non-existent HD stream. The "HD" version on the iPlayer site is not actually full HD, and it isn't the version that GiA attempts to download. All you can do is try again later to see if the HD version has been made available.
