### ISSUE TITLE
ITV Show Marcella Episode 6 fails to finish downloading

### ISSUE THREAD

**Issue by jefro108** [GetiPlayerAutomator/get-iplayer-automator#557]
The ITV Show Marcella Episode 6 consistently fails to finish downloading.

See verbose log: https://gist.github.com/jefro108/1b9506fc1df4af3e186525338ba04bbf#file-itv-marcella-episode-6-getiplayerautomator-log

Any ideas why?

I have no problems with other ITV programmes.

**Comment by dinkypumpkin** [comment]
Thanks for the log. It appears you simply encountered server problems. The server dropped a couple of your connections, and the problem was compounded for subsequent attempts because earlier partial downloads could not be resumed. It happens, and there is nothing you or GiA can do about it except try again later. Be sure to delete any partial downloads between attempts. It is not a problem with that specific programme - it downloads fine here.

**Comment by jefro108** [comment]
When I tried the download several times again it produced exactly the same file size of 420,927,095 bytes (421.1 MB on disk) each time. This consistency doesn't really indicate a server problem surely?

I updated to the latest pre version in case that changed things. Didn't.

Verbose log again https://gist.github.com/jefro108/ea17c5eceecda8736e78e14067c44cbd

**Comment by dinkypumpkin** [comment]
In that case, it might be a duff version of the media on whatever CDN edge servers are used for your location, but that is an uneducated guess. 

There was a similar report in #528. Below is an updated version of the advice I gave there, which seemed to do the trick. No guarantees it will work in this case, bit it won't do any harm.

Download this:

http://sourceforge.net/projects/get-iplayer/files/osx/utils/x86_64/20160402/get_iplayer-osx-utils-x86_64-20160402.zip

Make a backup copy of this:

/Applications/Get iPlayer Automator.app/Contents/Resources/rtmpdump-2.4

then replace it with rtmpdump from get_iplayer-osx-utils-x86_64-20160402.zip, renaming the file to rtmpdump-2.4

If GiA not installed in /Applications, adjust path accordingly

**Comment by jefro108** [comment]
Unfortunately I had the same size unfinished download  :(

Any other thoughts?

**Comment by dinkypumpkin** [comment]
Temporarily change your ITV format settings to download a lower-quality version. It may only be the highest-quality version that is screwed up.

**Comment by hugofalkman** [comment]
Also I can't download Marcella Episode 6 with the prerelease and the use current webpage button.

It fails consistently after a third of the file has been downloaded.

**Comment by hugofalkman** [comment]
No I am running a lower-quality version. My total file size i 330 MB and it fails after 118 MB.

**Comment by hugofalkman** [comment]
I asked a friend to download. Failed for him too.

**Comment by dinkypumpkin** [comment]
A final suggestion: Turn on verbose logging, attempt download until it fails, copy the full rtmpdump command from the verbose log, paste it at a command prompt and run the download outside GiA. It won't be more likely to succeed, but you may see some output that helps explain why it stops short. GiA discards some rtmpdump output. Beyond that, there is nothing more I can add. That programme downloads fine here in the UK.

**Comment by jefro108** [comment]
Thanks I've tried to use the rtmpdump command from the verbose log:

 "/Applications/Get iPlayer Automator.app/Contents/MacOS/rtmpdump-2.4" -r "rtmpe://cp72511.edgefcs.net/ondemand?auth=eaEaqaNcGbgcZdZa1bSa9b_bAdPaXdsc2dBduakbObzaBabaQcabsa2bIa3dKaRaack-bxnhSP-eS-axv3EBtlwuxp&aifp=v002&slist=production/" -W "http://www.itv.com/mediaplayer/ITVMediaPlayer.swf?v=11.20.654" -y "mp4:production/priority/CATCHUP/2/4269/0006/001/2-4269-0006-001_PC011800_16X9.mp4" -o "/Volumes/media/Downloads/TV Shows/Marcella/Marcella.s01e06.Episode 6.partial.flv" --verbose

but it fails almost immediately - see https://gist.github.com/jefro108/920e9de7d4eb60d496b782ee185c747b

**Comment by dinkypumpkin** [comment]
It looks like you pulled the rtmpdump command from the log you posted yesterday, which won't work. The  authentication tokens expire.

**Comment by hugofalkman** [comment]
Ok, I am not in UK -- using Unotelly's UnoDNS service, so not VPN. My friend is also using UnoDNS but from a different country.

**Comment by hugofalkman** [comment]
Watching Marcella Episode 6 directly on the ITV site there are several glitches starting about 15 minutes into the show. The screen goes black for a few seconds, then either Safari continues or Safari manages to reconnect after showing colored moving dots for a few seconds or Safari freezes the screen. In the latter case after reloading the page you can push the resume button to continue.

The glitches however are not consistently appearing every time. But the most consistent one of them all occurs at 21.00.

DP Do you see any of these glitches?

I like jefro108 get the exact same file size every time 118.1 MB out of approximately a 330 MB total file size.

**Comment by jefro108** [comment]
Done the rtmpdump from a new download session. The output is at https://gist.github.com/jefro108/fc17afa21b34471fe60de1bb371d8d9f

Still halts at 420,927,095 bytes, although says Got Play.Complete or Play.Stop from server. Assuming stream is complete.

**Comment by dinkypumpkin** [comment]
Thanks for testing. The problem appears to be at the ITV end - the media server is ending the stream before the entire programme is delivered. I don't know why it doesn't affect me unless we are consistently being routed to different CDN servers and only yours has a duff version of the programme. I've seen this happen with a few BBC programmes, and there is no solution that I'm aware of. Whatever the case, I'm throwing in the towel.

**Comment by hugofalkman** [comment]
Marcella episode 6 downloaded successfully today

**Comment by jefro108** [comment]
Thanks for all your help - now it's downloaded today after the next episode is out.
