### ISSUE TITLE
APP Update status

### ISSUE THREAD

**Issue by pstibbons** [GetiPlayerAutomator/get-iplayer-automator#558]
Given the recent events, i.e. problem downloading ITV programmes, will there be an update sooner than later?  Many thanks.

Alan

**Comment by blloyd78** [comment]
I have updated to the latest pre-release client, but my problems persist - namely "Problem Unknown" errors when attempting to download from ITV Hub.

What I would say is that the feed search *does* seem to work - for any programs that are not age restricted. Try search "knock" - adult program "The Knock" does not appear in search results, but kids program "Bottom Knocker Street" does.

Neither will download however - even if you use the "Use Current Webpage" button.

**Comment by dinkypumpkin** [comment]
@blloyd78 - have the courtesy not to hijack threads with unrelated issues. Create a new one if you want your problem looked at. Locking thread to avoid any more hijacking.
