### ISSUE TITLE
Use Current Webpage no longer working in 1.8.7-pre2

### ISSUE THREAD

**Issue by cdebaixo** [GetiPlayerAutomator/get-iplayer-automator#564]
I have recently downloaded and used the beta version 1.8.7-pre 2(1753) for itv downloads. Today, however, I tried downloading from http://www.itv.com/hub/the-secret/2a4185a0004 and received an 'Invalid Page..' message. I have tried reinstalling the beta version but to no avail. Is there a known issue here?

Thanks for your help.

**Comment by nitramlatep** [comment]
Yes, use pre3

**Comment by dinkypumpkin** [comment]
Duplicate of #561
