### ISSUE TITLE
Use Current Webpage not working with iPlayer

### ISSUE THREAD

**Issue by freddybobs** [GetiPlayerAutomator/get-iplayer-automator#569]
I have recently noticed that the Get Current Webpage feature is not working with iPlayer.  I get an 'Invalid Page' error.  The error message includes the URL for the program so it is picking up the right browser window.

I am using Safari 9.1.1 (11601.6.17)

**Comment by KevanV** [comment]
I have noticed the exact same behaviour that started immediately after I updated with security updates (29th May 2016).  I changed configuration to use Chrome and could get the current webpage.

**Comment by dinkypumpkin** [comment]
Use the latest pre-release build with Safari. See wiki for instructions.
