### ISSUE TITLE
iTunes does not recognise downloaded file ".partial.mp4.flv"

### ISSUE THREAD

**Issue by willson556** [GetiPlayerAutomator/get-iplayer-automator#57]
_From [adrian.g...@gmail.com](https://code.google.com/u/116724241153019356583/) on December 19, 2011 20:30:04_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? What version of the product are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/get-iplayer-automator/issues/detail?id=57_

**Comment by tomorrowbetter** [comment]
You may use iDeashare VideoGo to convert FLV, MP4, WMV, AVI, MKV, AVCHD, RMVB etc to iTunes supported format.
Step by step guide at http://www.idealshare.net/itunes-quicktime/convert-flv-to-itunes.html
