### ISSUE TITLE
Cannot download TV Show

### ISSUE THREAD

**Issue by user182015** [GetiPlayerAutomator/get-iplayer-automator#571]
I use the current webpage option to try and download a show from ITV: Good Morning Britain (Tuesday 7 June). It won't download at all - it gets to 0.1% and stops.

I am using Mac and the latest prerelease of GiA.

**Comment by dinkypumpkin** [comment]
Cannot reproduce. Re-read what I already told you in #567, and please don't make me repeat myself again.

**Comment by user182015** [comment]
Sorry! I forgot. To reproduce the issue, use the current webpage feature on Good Morning Britain (Tuesday 7 Jun). Start the downloads, it will start and go to 0.1%, then say initialising RTMPDump. Using the latest version of Mac OS X and the latest prerelease of GiA. I am not using a proxy or anything like that. I hope this helps.
[GiA Log.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/312836/GiA.Log.txt)

**Comment by dinkypumpkin** [comment]
I meant [this](https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues/567#issuecomment-222148963):
> ...understand that all downloads can be unreliable. Sometimes the problem is at the ITV end and sometimes it lies with your upstream connection. There is nothing GiA can do about either. You just have to delete any previous partial download and try again. It is highly likely you would be wasting your time and ours by creating a new ticket for this issue.
