### ISSUE TITLE
Getting a 30-day BBC cache?

### ISSUE THREAD

**Issue by mostlyotter** [GetiPlayerAutomator/get-iplayer-automator#573]
I have two versions of GiA: 1.3.7.1 on Snow Leopard 10.6.8 (for radio) and 1.8.7-pre.3 on Yosemite 10.10.5 (for TV).

GiA 1.3.7.1 has a version of get_iplayer.pl downloaded on 07 March 2016. With quick-caching unchecked, the BBC TV and radio caches go back about 30 days, but with the same settings, 1.8.7-pre.3 only has a 7 day cache.

If I transfer the 1.3.7.1 tv.cache to 1.8.7-pre.3, then the 30-day cache lasts until the next cache refresh.

Is there a simpler way of getting a 30-day cache into 1.8.7-pre.3?

**Comment by dinkypumpkin** [comment]
It doesn't really help to say "downloaded on 07 March 2016" - any version of get_iplayer could be downloaded on a given day. I'll assume you've downloaded the development version of get_iplayer from that date. That is unreleased and unsupported code, so you won't get it in GiA unless you put it there. You can't just transfer the cache file to 1.8.7-pre.3 and expect it work without also transferring the code that maintains it.
