### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by pstibbons** [GetiPlayerAutomator/get-iplayer-automator#574]
Do you have a tutorial that explains how I can download the beta version of Get iPlayer Automator and not delete the current app. Any help is appreciated.

Cheers!
Alan

**Comment by dinkypumpkin** [comment]
There is no beta per se. Access to pre-release builds is explained in the wiki

**Comment by pstibbons** [comment]
Hello, 

To follow up, it is not clear how to proceed.  Could you show an example where two live together?  Thanks. 


-------------------
You do not need to replace the current release of GiA with a pre-release build. You may install it in an alternate location and run it separately in order to test bug fixes and new features. A pre-release build will use the same preferences as the current release version, so exercise care when switching between pre-release builds and the current release.

**Comment by larryy** [comment]
Get iPlayer Automator is a relatively normal Mac application.  If you want two different versions, just name them differently.  So if the current release is 1.x.y and the pre-release is 1.x.z, just name the current release Get iPlayer Automator 1.x.y.app and the pre-release version Get iPlayer Automator 1.x.z.app.  Launch whichever one you want to use at the moment.  Or launch them both (though I'm not sure about doing downloads in both at the same time, though even that probably works).  Roberta's your auntie.

**Comment by pstibbons** [comment]
Many thank, Larry!
