### ISSUE TITLE
BBC TV content not downloading

### ISSUE THREAD

**Issue by naq59** [GetiPlayerAutomator/get-iplayer-automator#576]
Since  8 or 9.7 I can´t download BBC TV programmes using the Get iPlayer Automator although I can watch them online via the BBC iPlayer. Radio content downloads fine as does ITV. I´m not sure whether this is a proxy issue from my overplay Smart DNS or something with the Get iPlayer Automator. Maybe the BBC has fiddled with their settings.

**Comment by dinkypumpkin** [comment]
GiA is working fine, so it must be your proxy.

**Comment by naq59** [comment]
Thanks for the quick reply. I´ve written to Overplay and I´ll see what they have to say.
