### ISSUE TITLE
GIA not connecting at all

### ISSUE THREAD

**Issue by Richbam** [GetiPlayerAutomator/get-iplayer-automator#579]
Have you searched all open and closed tickets to check if your issue has already been reported? If not, use the search box at the top of the page to do so. If you create a ticket for an issue that has already been reported, it will be marked as a duplicate and closed with no further action. If you are certain your issue has not yet been reported, follow the instructions below.

Create a succinct title describing your issue in the Title field above, then provide the information requested below. If you do not provide the requested information, your ticket may not receive a response.

What steps will reproduce the problem? Be specific, and provide as much detail as possible.

What is the expected output? What do you see instead?

What version of GiA are you using? On what version of OS X?

Are you using a web proxy? DNS proxy? VPN? VPS?

What programme are you attempting to download (full title, series and episode)? **Provide only ONE programme as an example. DO NOT list multiple programmes.**

If you cannot download a programme, provide a verbose log of the attempt. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE programme. DO NOT post a massive log covering multiple multiple programme downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

Please provide any additional information below.

**Comment by dinkypumpkin** [comment]
If you can't be bothered to provide any of the requested information, don't expect a response.

**Comment by Richbam** [comment]
My apologies. I am new to GitHub and was intending to add detail plus a verbose log, but hit the wrong button and just the title posted. 
Richard Bambridge
richandaddie@gmail.com
