### ISSUE TITLE
ITV Hub Download Fails

### ISSUE THREAD

**Issue by user182015** [GetiPlayerAutomator/get-iplayer-automator#583]
This is an issue not like the previous ones I've written about. ITV Hub recently uploaded all of Series 1 of Love Island and I would like to download it, but as soon as you click start in GiA, the download fails immediately. This happens with every episode of Series 1 - but I can still download Series 2 episodes.

Link to Seires 1 | Episode 1 -> http://www.itv.com/hub/love-island/2a3697a0001

**Comment by dinkypumpkin** [comment]
Works fine here. Read this and see if it applies to you:

https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Using-GiA-in-the-UK
