### ISSUE TITLE
Download Completed Error 

### ISSUE THREAD

**Issue by user182015** [GetiPlayerAutomator/get-iplayer-automator#584]
Love Island - Series 1 Episode 12 (http://www.itv.com/hub/love-island/2a3697a0012) doesn't download at all, yet its status in the queue is "Download Completed" and then the next item in the queue will download. A file is created for this episode but it is zero bytes. Any ideas on how to correct this?

**Comment by dinkypumpkin** [comment]
If you continue to ignore the instructions, don't expect a response.

**Comment by user182015** [comment]
Why did you add cannot reproduce - all you have to do is add the item into the list using the current webpage feature and the URL I provided you with. What instructions am I supposedly ignoring?

**Comment by dinkypumpkin** [comment]
"Cannot reproduce" = cannot reproduce the problem, thus not a GiA issue, thus ticket closed.
