### ISSUE TITLE
For Developer Info Only - Post 1.8.7-pre.3 + iTunes 12.4.2.4 32 Bit Issue

### ISSUE THREAD

**Issue by Radar68** [GetiPlayerAutomator/get-iplayer-automator#585]
Just for info for the developer as this is unsupported version of GiA.

Issue is present in pre.4 and new pre.5 - pre.3 is unaffected and still works.
When downloading and having GiA add programme to iTunes, GiA upon completion now reports that file could not be added to iTunes and a fix is to run iTunes in 32bit mode (something that isn't possible in El Capitan and iTunes 12 as far as I am aware).
iTunes was updated last week to v12.4.2.4 so I'm guessing this has broken something in pre.4 and pre.5
The combination of new iTunes and pre.3 is fine.
Happy to supply any other info needed though I think above should be sufficient.  I also have test rig running macOS Sierra and iTunes 12.5 if I can do any testing there please let me know.

**Comment by dinkypumpkin** [comment]
Thanks for the heads-up. Integration of get_iplayer 2.95 was the culprit. GiA needs some more work in that area, so I've temporarily rolled back to get_iplayer 2.94 for pre-release builds.
