### ISSUE TITLE
Audio Described Issue

### ISSUE THREAD

**Issue by user182015** [GetiPlayerAutomator/get-iplayer-automator#589]
I'm trying to download 'Red Rock - Episode 1' from BBC iPlayer with AD (Audio Description) and the AD checkbox is ticked in GiA preferences. The programme downloads perfectly but when it is complete there is no audio description on the file and it is the standard version. In the GiA log: "None of the modes in your download format list are available for this show." Any ideas?

**Comment by user182015** [comment]
Why is this issue now closed?

**Comment by Vangelis66** [comment]
@user182015 wrote:

> Why is this issue now closed?

https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Reporting-Issues
and more importantly:

> Before creating a new ticket, search the current open and closed tickets to see if your issue has already > been reported. Use the search box at the top of the page to do so. You can also use the links below to > view open and closed tickets in list form. 

Had you done that, you'd have found:
https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues/442
duplicate of: 
https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues/410

Hope your question is answered now...
