### ISSUE TITLE
Download format not available for SWE v RSA women's football

### ISSUE THREAD

**Issue by user182015** [GetiPlayerAutomator/get-iplayer-automator#590]
I cannot download - Olympic Football: 2016: Sweden v South Africa - Women's First Round (on BBC) as it says that "None of the download formats you specified were available for this show. Please add more download formats to your list in preferences."
In preferences I have got all the available BBC formats enabled in order from HD to Low. The programme itself is available as HD and SD on iPlayer but I can't seem to download it. The URL for the programme is: http://www.bbc.co.uk/iplayer/episode/p041v8tp/olympic-football-sweden-v-south-africa-womens-first-round

**Comment by dinkypumpkin** [comment]
You won't be able to download that programme. The Flash formats supported by GiA are not available, only HLS. It's too early to say, but this will likely be true for other Olympics programmes. You'll need to use get_iplayer itself.

**Comment by user182015** [comment]
How can I use get_iplayer itself?

**Comment by user182015** [comment]
DinkyPumpkin can you tell me how to find get_iplayer on Mac?

**Comment by Vangelis66** [comment]
@user182015 wrote: 
> **DinkyPumpkin** can you tell me how to find get_iplayer on Mac?

I am not dinkypumpkin, but without sounding rude, 
why do you expect other people to do the job for you? 
Don't your Mac skills include searching via your favourite 
search engine in a browser? 

https://squarepenguin.co.uk/wiki/osx/

Please. post installation, read all guides  available at: 
https://squarepenguin.co.uk/faqs/
https://squarepenguin.co.uk/guides/
https://squarepenguin.co.uk/wiki/

DO NOT POST get_iplayer queries here; 
the show you're after (pid=p041v8tp) will be on 
iPlayer for a whole month, so you have ample time 
to familiarise yoursef with get_iplayer. 

In the event you hit a dead end, post only at 
https://squarepenguin.co.uk/forums/forum-9.html
(there's also a user-based mailing list at: 
http://lists.infradead.org/mailman/listinfo/get_iplayer 
with at least one frequently posting Mac user - not me!)

**Comment by arijitsadhu** [comment]
The latest get_iplayer Release 2.96 seems to download BBC Olympic programmes fine, the version in  GetiPlayerAutomator uses get_iplayer Release 2.94 throws the error "No specified modes". Unfortunateley it is not a a drop in replacement, GetiPlayerAutomator fails with this version of get_iplayer, assume some parameters changed.
