### ISSUE TITLE
Olympic programmes available on BBC iPlayer but not shown on BBC 1, 2 or 4 are processable/available but not in any format offered by G-iP-A

### ISSUE THREAD

**Issue by onetwo99** [GetiPlayerAutomator/get-iplayer-automator#593]
Olympic programmes available on BBC iPlayer but not shown on BBC 1, 2 or 4 are available (with a PID) but an error is produced to say that none of the selected formats works (e.g. Hi Def, High, Low, etc). 
Try e.g. the programmes at http://www.bbc.co.uk/iplayer/episodes/b00cpqlk

**Comment by dinkypumpkin** [comment]
duplicate of #590
