### ISSUE TITLE
Feature Request: Save safety copies of history and PVR queue

### ISSUE THREAD

**Issue by Moisie2000** [GetiPlayerAutomator/get-iplayer-automator#598]
Hello again:

Every so often - with no discernible cause - my history and PVR queue files get corrupted. Luckily I can usually restore them from a recent Time Machine backup. However, it would be great if:
- Obviously, causes of corruption can be squashed - though I know this is more easily said than done;
- As a safety net, keep backup copies of the history and PVR queue files, recognise corruptions of the current files and restore the backups if necessary.

Thanks.

**Comment by willson556** [comment]
There are probably better ways we could be storing the queue files than the current binary approach. I'll look into this for the next release.

**Comment by jefro108** [comment]
I vote for this - I just had to restore from Time Machine the PVR queue file Queue.automatorqueue from a couple of days ago (before it got corrupted).
