### ISSUE TITLE
Feature Request: PVR / Main search window integration

### ISSUE THREAD

**Issue by Moisie2000** [GetiPlayerAutomator/get-iplayer-automator#599]
Hello again:

Two requests to improve integration between the PVR window and main search window:
- I'd love to be able to add a programme to the PVR from the main search window, without having to re-search for the programme in the PVR window;
- It would be helpful to flag already-existing PVR entries in the main search window. My PVR list is massive, and I sometimes end up adding programmes to it twice.

Thanks.

**Comment by willson556** [comment]
@Moisie2000 It probably doesn't make a lot of sense for us to have the separate search in the PVR window at all. So we should probably remove that and just let users use the main window and move the auto-record button.

As for the second item, the PVR manager isn't supposed to eat you add a duplicate...however looking back at that code there's clearly a bug. That's now been fixed.
