### ISSUE TITLE
Update to Safari 10.0 causes hang after download

### ISSUE THREAD

**Issue by Tony3000** [GetiPlayerAutomator/get-iplayer-automator#600]
Using GiA version _1.8.7 on OS X 10.11.6

Recent push update to Safari 10.0 causes GiA to hang after downloading, necessitating a force quit to close the main window.

Using GiA 1.8.7 on another machine without the Safari update operates as expected.
No proxies being used.

**Comment by dinkypumpkin** [comment]
Cannot reproduce. Moreover, Safari is not connected to downloading in any way.

**Comment by Tony3000** [comment]
Thanks for the feedback. It looks like the executable(s) got corrupted at the same time as the Safari download. I re-installed GiA from scratch & problem is resolved.
