### ISSUE TITLE
Unable to download since OS upgrade

### ISSUE THREAD

**Issue by depechedaz** [GetiPlayerAutomator/get-iplayer-automator#602]
Ive had the Get iPlayer app on my Mac for quite a while and had no problems, but last week I had to do go back to factory setting on my MacBook Pro as the downloading of the new Sierra OS basically buggered my laptop up so I lost everything.
After successfully getting the computer back up and running and installing the new OS I re-installed get inlayer but now I can't download anything. I just get a box appear saying "Problem Unknown" "Submit a bug report...which I have by the way.
I restarted the computer to see if that works which it doesn't and I've un-installed the app and re-installed it but still no luck.
OS Sierra 10.12
Get iplayer version 1.8.7 (1793)
![untitled](https://cloud.githubusercontent.com/assets/22745568/19236037/1846b636-8eed-11e6-9e07-a7d2e184f340.jpeg)

**Comment by nigelbb** [comment]
I have a similar issue but I have not upgraded to Sierra & am still running OS X 10.11.6 on my MacBook Pro Retina Late 2013 model. I cannot download any programme & get the same enigmatic "Problem Unknown..." error. I have submitted a bug report. I have tried uninstalling & reinstalling without success but merely dropping the executable into the Trash clearly doesn't do a complete uninstall as my previous preferences remain.

I welcome any suggestions for fixing or further debugging or how to completely uninstall all traces before reinstalling.

**Comment by depechedaz** [comment]
I had a play around in the preferences and changed the proxy to none and ticked the use proxy for all activities box and now its seems to be working

**Comment by nigelbb** [comment]
Thanks! I too changed proxy to none and ticked the use proxy for all activities box and now its seems to be working again.

**Comment by dinkypumpkin** [comment]
The "use proxy for all activities" option has no effect with proxy = None, as you would expect.

**Comment by depechedaz** [comment]
By "proxy" does that mean it my IP address is still hidden and another one is automatically used?

**Comment by nigelbb** [comment]
I can confirm that just setting proxy to none fixes the problem & setting it back to 'Provided' causes the "Problem Unknown..." error & failed downloads.

I have never used a proxy nor had I changed the Get iPlayer Automator preferences which must have always been set to 'Provided' so something external to this programme must have changed to cause the problem.
