### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by cadzow** [GetiPlayerAutomator/get-iplayer-automator#603]
Tried to run get iPlayer automator on MacOS (the new OS) and it doesn't work. It simply hangs. I've gone back a couple of versions and v1.8.5 appears to work (albeit slowly). Nothing so far has apparently mentioned MacOS compatibility (the requirement is OSX10.7 or later).

**Comment by robincm** [comment]
I have 2 MacBooks, both running MacOS Seirra and have no problems at all.
I wonder if you need to completely remove GiA and do a clean install.

https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Clean-Install

good luck.
