### ISSUE TITLE
All BBC TV download attempts fail

### ISSUE THREAD

**Issue by mattprice100** [GetiPlayerAutomator/get-iplayer-automator#607]
I am using the latest version of GPA 1.8.7 and all my BBC download attempts fail. I am on MacOS Sierra
I have tried different programme downloads to see whether it was programme specific but happens to all. One of the fails is 'Close to the Enemy Ep1"

[Required information not supplied by user]

**Comment by simonbruce** [comment]
I too am suffering with this problem, should we be worried?

**Comment by ElsonRoa** [comment]
I have this issue too. But I can still download from the BBC's radio sites with no problem. How odd!

**Comment by ElsonRoa** [comment]
Ok, I have been playing around with connections and I have concluded this is not a Get Iplayer problem. Though I am in the UK, I use a VPN just for general security. Get Iplayer has stopped working with the Private Internet Access VPN. It works ok with no VPN. It also works ok with the Trust.info VPN.

**Comment by ElsonRoa** [comment]
I contacted PIA. Here is there reply:

_As you may have noticed, our UK servers (London and Southampton) are currently listing Netherlands IP addresses.

This is part of initial changes we have enacted on our network in response to the Investigatory Powers Bill which passed Royal Assent on 29 November 2016.

We will send an email in the near future detailing our response to the Investigatory Powers Act, including the steps we are making moving forward, but at this time I cannot release any further information.

I apologise for the limited information at this time, but please be assured that we are taking steps to ensure your privacy and security are maintained._


..so, mattprice and simonbruce, if you happen to be using PIA, that is the problem.

**Comment by mattprice100** [comment]
I use no VPN although have tried it with Tunnelbear that i occassionally use and it does not work. My IP is VirginMedia could they be blocking ?

**Comment by ElsonRoa** [comment]
I'm not sure about Virgin. It's possible. I've had problems with them in the past - the way they assign IP blocks, it sometimes appears one is outside the UK even when one is in it. I assume you've used a geolocation service to find out where your IP is registered? (Ie if you 'appear' in the UK or not). But I think that's the only way Virgin might stop you. They'd not block get iplayer specifically. 

But as I said above, I don't think it is a get iplayer issue. My get iplayer is working fine now.

**Comment by simonbruce** [comment]
I don't use PIA (had to look it up as I couldn't understand where Pakistan Airlines Figured) but I do use a Smart DNS provider as I am geographically challenged with regard to UK television!
However I don't think that is the issue as I have no problem watching BBC programmes using iPlayer, live or recorded; only using GiA to download them.
I did try using the VPN but that makes no difference.

**Comment by hugofalkman** [comment]
All Smart DNS providers that successfully provide BBC and ITV services don't work with GiA.

For instance Unblock-us doesn't. At the moment Unotelly does. 

Hälsar Hugo från sin iPhone
070 663 3226

**Comment by ElsonRoa** [comment]
simonbruce - I don't have the tech skills to decode the report. And I think you're meant to submit a GIA verbose report as an attached .txt file - pasting it into the issue report, I think, will likely get it deleted.

As I mentioned before GIA works on some of my connections and not on others. But I can download BBC programs on all connections using the BBC's native DL program. 

I'm fairly sure this is an IP/DNS problem and not a GIA problem; and therefore I would not expect any reaction to this thread from the GIA team. They are - rightly - really quite strict about what they reply to and what they don't.

**Comment by Vangelis66** [comment]
@mattprice100, please read https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues/580#issuecomment-235450172

Either your SmartDNS service has ceased supporting iPlayer RTMP streams, 
or the BBC have blacklisted the DNS servers delegated to the RTMP streams; 
in either case, not a GiP/GiA issue. 

Additionally, a recent amendment to the wiki  is [denying support](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/No-Support-for-GiA-Outside-the-UK) 
to overseas GiA users; and it looks as though you haven't read 
the issue reporting guidelines [here](https://github.com/GetiPlayerAutomator/get-iplayer-automator/blob/master/.github/ISSUE_TEMPLATE.md) and [here](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) either; 
I prophesy your issue will be swiftly closed by the tracker maintainer...
