### ISSUE TITLE
Sherlock: Series 4 - The Final Problem: "This show could not be located on iplayer/ITV Player"

### ISSUE THREAD

**Issue by Doctorjock** [GetiPlayerAutomator/get-iplayer-automator#608]
---

What steps will reproduce the problem? Be specific, and provide as much detail as possible.
1. Search for Sherlock
2. Click Sherlock: Series 4 - The Final Problem
3. Click Add To Queue
4. Click Start 

What is the expected output? What do you see instead?
I expected the show to start downloading but instead received the message "This show could not be located on iplayer/ITV Player"

What version of GiA are you using? On what version of OS X?
GiA - 1.8.7
OS X - Sierra 10.12.2

Are you using a web proxy? DNS proxy? VPN? VPS?
No

What programme are you attempting to download (full title, series and episode)? **Provide only ONE programme as an example. DO NOT list multiple programmes.**
Sherlock: Series 4 - The Final Problem

If you cannot download a programme, provide a verbose log of the attempt. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE programme. DO NOT post a massive log covering multiple multiple programme downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**
[GiA Log.txt](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/726702/GiA.Log.txt)

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

Please provide any additional information below.

**Comment by dinkypumpkin** [comment]
Works fine here. Your log indicates that the programme metadata was temporarily unavailable from BBC servers. There is nothing GiA can do about that, but it's usually a transient condition. Try the download again over the next few days.
