### ISSUE TITLE
BBC Subtitles lack colours

### ISSUE THREAD

**Issue by darrenbyrne** [GetiPlayerAutomator/get-iplayer-automator#609]
Hi,

What steps will reproduce the problem? Be specific, and provide as much detail as possible.

When viewing programmes on the BBC iPlayer or the ITV hub, subtitles are in colour. When downloading subtitles on GiA, the resulting .srt includes colour tags, but the BBC .srts do not include the colour tags. The xml source of the subtitles contains colour tags and putting the xml through ttml2srt.py results in colour tags in the .srt.
Changing the hidden preferences for ITV_SRTIgnoreColors does not impact the result. I have also tried to set SRTIgnoreColors (in case this is getting called) but to no avail.

What is the expected output? What do you see instead?
 I anticipated that colour subtitles should continue through the process if they are present in the source.

What version of GiA are you using? On what version of OS X?
I have tried 1.8.7, 1.8.7-pre.3 and 1.8.8-pre.4. I am using OS X 10.12.3

Are you using a web proxy? DNS proxy? VPN? VPS?
I have when in the UK and using a VPN.

What programme are you attempting to download (full title, series and episode)? 
Taboo, Series Episode 6.

If you cannot download a programme, provide a verbose log of the attempt. 
N/A.

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. 
N/A.

Please provide any additional information below.
I have checked through get-iplayer-automator-master looking for some preference option that could be called but cannot seem to isolate and option that would apply to BBC. 

Thanks.

**Comment by dinkypumpkin** [comment]
get_iplayer doesn't preserve colours in subtitles. Leading hyphen is used to indicate change of speaker. Only ITV subtitles are processed with ttml2srt.py.

**Comment by dinkypumpkin** [comment]
I should also point out that colour changes in BBC subtitles are generally not very useful. They typically don't track speakers through multiple titles, but rather only indicate a speaker change within a single title.

**Comment by darrenbyrne** [comment]
That's cool, thanks for the clarification - just making sure that I wasn't doing anything incorrectly. 

As a Deaf household, we use subtitles on everything and in our circumstances colour is always preferable to hyphens - from an access perspective.
