### ISSUE TITLE
cut out after approx one hour

### ISSUE THREAD

**Issue by Cabinet123** [GetiPlayerAutomator/get-iplayer-automator#610]
I've just download Get_player automator to a friend's AppleMac Air.

It works fine for programs up to an hour, but a longer program will cut out around the hour mark.

(I've got Get_player on my Windows 7 machine - and this problem there was solved by using exclude-supplier=akamai.  But that's probably irrelevant!  It's a similar problem, though.)

Apologies if this has already been answered anywhere.  I did look, and couldn't see any sign of this  particular issue coming up.

**Comment by dinkypumpkin** [comment]
Works fine here. Since you couldn't be bothered to provide an example to test, there isn't anything else to say.
