### ISSUE TITLE
"Permanently skip selected series-link entries" not working

### ISSUE THREAD

**Issue by Adlopa** [GetiPlayerAutomator/get-iplayer-automator#611]
New install of 1.8.7 (1793) on macOS 10.12.3.

When series-linked BBC radio shows (i.e. those in PVR Manager) are added to the queue and then either downloaded or skipped, they are re-added the queue when the app is next run and series links updated. My understanding is that they should be permanently removed unless manually deleted from the download history.

Nothing in the log other than:

"Get iPlayer Automator 1.8.7 Initialized.

Updating Program Index Feeds from Server...
AppController: Index was Up-To-Date."

**Comment by dinkypumpkin** [comment]
Works fine here. Since you couldn't be bothered to provide an example to test, there isn't anything else to say.
