### ISSUE TITLE
Unable to download iPlayer programmes (GiA broken by BBC changes)

### ISSUE THREAD

**Issue by thomasp132** [GetiPlayerAutomator/get-iplayer-automator#612]
When I try to download programmes from iPlayer, the download fails and I get the following error in the logs. The programme can be watched on iPlayer.

I'm using version 1.8.7 of Get iPlayer Automator, on OSX 10.11.6. It seemed to work fine last week, and nothing to my knowledge has changed.

```
"INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=b08jns7r): Downloading Robot Wars: Series 9 - Episode 2
INFO: pid found in cache
5367:	Robot Wars: Series 9 - Episode 2, BBC Two, , default
INFO: 1 Matching Programmes
WARNING: Could not download programme metadata from http://www.bbc.co.uk/programmes/b08jns7r.xml
ERROR: Failed to get version pid metadata from iplayer site
BBC Download (ID=b08jns7r): Robot Wars: Series 9 - Episode 2 Failed

AppController: Downloads Finished"
```

**Comment by dinkypumpkin** [comment]
The BBC has removed some data sources necessary for get_iplayer to work. The problem also affects programme indexing and cache refresh. It may be a temporary situation, but there is no way to know for sure what they are doing. For the moment, just don't use GiA for iPlayer programmes (ITV programmes shouldn't be affected). There will be an announcement here if/when the BBC data returns.

**Comment by dinkypumpkin** [comment]
Normal service resumed.
