### ISSUE TITLE
Here's an alternative downloader until BBC iPlayer feed changes are figured out

### ISSUE THREAD

**Issue by gingerbeardman** [GetiPlayerAutomator/get-iplayer-automator#613]
http://www.jdownloader.org

I just downloaded yesterday's Rad/Mac programme using it
http://www.bbc.co.uk/programmes/b08h944g

Other users may find this useful. Hope it's OK to post it here.

**Comment by edjonesy** [comment]
I just tried to dl 'the replacement' episode three using that, I get a message about the file being offline :(

**Comment by dinkypumpkin** [comment]
Post JDownloader issues in its forums. Thread locked.
