### ISSUE TITLE
GIA Still Refusing to Download Programmes

### ISSUE THREAD

**Issue by SwaleSwimmer** [GetiPlayerAutomator/get-iplayer-automator#616]
Hello, After last week's BBC iPlayer problem, which I understand has been resolved, I cannot download programmes. I was using GIA 1.8.7 when the problem arose, I then tried 1.8.8.pre4 and now back to 1.8.7 all to no avail.

Please can anybody throw some light on my problem or suggest a solution. I have attached the log file.

Thanks in advance.
[Get_iplayer download failure.pdf](https://github.com/GetiPlayerAutomator/get-iplayer-automator/files/855825/Get_iplayer.download.failure.pdf)

**Comment by dinkypumpkin** [comment]
If you're not in the UK, you're blocked and out of luck. If you are in the UK, don't use the proxy.
