### ISSUE TITLE
'No shows found'  (BBC) / 'Unknown: PID Not Found' / Web site down / Software updates broken / Feedback broken / Invalid proxy host / Failing downloads / Everything else that is wrong with GiA

### ISSUE THREAD

**Issue by thomasp132** [GetiPlayerAutomator/get-iplayer-automator#617]
I'm using v1.8.7 of GiA and I can't search for any shows. Type anything in and it comes up with an error message saying no shows found. If I Try the 'use current webpage' feature that also fails, with the following log entry:

`AppController: Starting Downloads
b08ljzb3: Robot Wars - Series 9: Episode 5: Retrieving Metadata For PID

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

Downloading Show 1/1:

BBC Download (ID=b08ljzb3): Downloading Robot Wars - Series 9: Episode 5
ERROR: Programe Type '' does not exist. Try using --refresh
BBC Download (ID=b08ljzb3): Unknown: PID Not Found Failed

AppController: Downloads Finished`

Also, it won't let me check for updates to the software, saying an update error occurred while retrieving information.

**Comment by kitscaboodle** [comment]
I am also having this exact same issue as of today.

**Comment by dantellocy** [comment]
Just go to settings/quick caching(BBC Only) and UNCHECK it. Works fine..downloading right now.

**Comment by thomasp132** [comment]
That seems to have fixed it, thanks for the reply :)

**Comment by jimjar** [comment]
Same problem. None of the fix suggestions work for me. I've found GiA invaluable on many occasions. Great utility - be very sad if it withers away.

**Comment by latenightlizzie** [comment]
Many thanks to @dantellocy and @dinkypumpkin for the tips posted on April 5th.  These have resolved the issue I had where I was unable to search or download anything on Get iPlayer 1.8.7 on a Mac running El Cap 10.11.6.

**Comment by OBEngineer** [comment]
Despite trying all the suggestions previously mentioned, nothing works for BBC iPlayer.
We're using:-
10.11.6 El Cap., 
1.8.7 GiA (1793).
Like everyone else, we think it's such a useful utility. We hope that we can make it work soon. 
It's very frustrating- it goes so far and then throws the 'Error' message.

**Many thanks to all involved**. It's much appreciated by those of us who don't know much about Macs!

**Comment by dantellocy** [comment]
Hi Folks,

Even though the caching has changed, you still need a working proxy server. Do not choose “Provided” under Preferences/Proxy. Provide your own WORKING(Custom) proxy. I’m on a mac 10.11.6, and using GiA Version 1.8.8-pre.4 (1802). It’s working. It will sometimes go through the motions a few times before downloading, but that’s the proxy server/bbc server’s coordinating the download, not me (or you if setup correctly). It does still work. You could go and delete GiA completely, including user/library/preferences file (it might help, but doubtful), then re-install clean. Remember to uncheck quick caching, then go to “file/force cache update” to get the most current show info. Don’t rely on automatic cache updates, always go with a manual force.

All of this depends really on exactly what “error” one is getting. Without seeing the context of the ERROR message, I can’t tell you more. 


Sincerely,


David Antellocy

“You are not entitled to your opinion. You are entitled to your informed opinion. No one is entitled to be ignorant.”

-Harlan Ellison

**Comment by OBEngineer** [comment]
I set my MAC up to grab the error message..... but it never materialised. The error message didn't appear. 
Because the Get iPlayer Automater worked!

I wish I could explain why.

I tried to d/l the later version from Sourceforge etc, but I wasn't able to access it.

**Comment by OBEngineer** [comment]
![img_2591](https://cloud.githubusercontent.com/assets/27033967/24970060/3c784ed2-1fb3-11e7-8656-12e006789536.jpeg)

For what it's worth, here is a grab- basic!- of my GiA Preferences settings.

It's worked...

**Comment by hugofalkman** [comment]
Having unchecked the Quick Cache (BBC only) option in preferences, BBC downloads still occasionally fail. Choosing Force Cache Update in the File menu followed by selecting the failed download and clicking the Process PID button so far has allowed the download to restart successfully.

**Comment by Lordsnooty05** [comment]
Guys, thanks so much for these ideas to fix GIA.....it definitely works for me. Hopefully the developer will get his Website up and running but in the meantime this is doing the job for me. I am doing what you said and unchecking the Quick Cache and going to file and choosing Force Cache Update and it worked for me.
Thanks again for all your help

Harry

**Comment by byshieldmaiden** [comment]
Ghost, I love you. The recommendations worked and I'm downloading right now. (Couldn't do without my Mary Berry everyday. :D)

**Comment by gingerbeardman** [comment]
Thanks @ghost !

If the app gets another update a "news" section about hot fixes like this might be a good thing to have.

**Comment by MatzFan** [comment]
@ghost's fix worked for me. Expiration of  [tom-tech.com](tom-tech.com) domain referenced in this repo's title on 3rd April is the cause, I guess. Hope maintainer can resurrect/replace it ASAP - not least as included the donations link :wink:

**Comment by dinkypumpkin** [comment]
Closed by #631
