### ISSUE TITLE
unknown:PID not found

### ISSUE THREAD

**Issue by ElersMid** [GetiPlayerAutomator/get-iplayer-automator#618]
**This issue tracker is not a discussion forum, so don't use it as such.  If you wish to discuss the BBC, iPlayer or anything else that is not related to an actual problem with the current release of GiA, post in an appropriate forum, not in this issue tracker.**

**STOP! DO NOT submit a ticket if you are unable to download a programme from outside the UK**. 

If you need an explanation, read [this](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/No-Support-for-GiA-Outside-the-UK). If you ignore this instruction, your ticket will be closed with no further action. You can fib about your location if you like, but you will only be wasting your time. If you are using GiA within the UK, continue with the instructions below.

Before creating a new ticket, search the current open and closed tickets to see if your issue has already been reported. Use the search box at the top of the page to do so. You can also use the links below to view open and closed tickets in list form. 

#### [Closed tickets](https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues?q=is%3Aissue+is%3Aclosed)

If you create a ticket for an issue that has already been reported, your ticket will be closed with no further action. If you are certain your issue has not yet been reported, continue with the instructions below.

Create a succinct title describing your issue in the `Title` field above, then provide the information requested below. If you do not provide the requested information, your ticket will be closed with no further action.

Delete the instructions above before submitting your ticket.

---

What steps will reproduce the problem? Be specific, and provide as much detail as possible.

What is the expected output? What do you see instead?

What version of GiA are you using? On what version of OS X?

Are you using a web proxy? DNS proxy? VPN? VPS?

What programme are you attempting to download (full title, series and episode)? **Provide only ONE programme as an example. DO NOT list multiple programmes.**

If you cannot download a programme, provide a verbose log of the attempt. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE programme. DO NOT post a massive log covering multiple multiple programme downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

Please provide any additional information below.

**Comment by dinkypumpkin** [comment]
Closed by #631
