### ISSUE TITLE
BBC issues downloading - is this known?

### ISSUE THREAD

**Issue by user182015** [GetiPlayerAutomator/get-iplayer-automator#619]
I cannot download any BBC content.
I've used the Use current webpage feature and then start the download.
Then, there it says 'Unknown: PID Not Found' and won't download.
ITV shows are fine.

Is this a known issue? How can it be resolved?

**Comment by user182015** [comment]
Sorry. It appears to have rectified itself. You may disregard this issue.

**Comment by dinkypumpkin** [comment]
Closed by #631
