### ISSUE TITLE
Main website (http://tom-tech.com/iplayer) is 'down'.

### ISSUE THREAD

**Issue by pavlovich** [GetiPlayerAutomator/get-iplayer-automator#621]
What steps will reproduce the problem? Be specific, and provide as much detail as possible.

**1. go to http://tom-tech.com/iplayer
2. Note the caption stating that the domain has expired and that the website is now a 'placeholder' page.**

What is the expected output? What do you see instead?

**I expected to see the tom-tech website.**

What version of GiA are you using? On what version of OS X?

**Not relevant.**

Are you using a web proxy? DNS proxy? VPN? VPS?

**No.**

What programme are you attempting to download (full title, series and episode)? **Provide only ONE programme as an example. DO NOT list multiple programmes.**

**Not relevant.**

If you cannot download a programme, provide a verbose log of the attempt. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE programme. DO NOT post a massive log covering multiple multiple programme downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

**Not relevant**

Please provide any additional information below.

**None.**

**Comment by dinkypumpkin** [comment]
Closed by #631
