### ISSUE TITLE
BBC Iplayer - PID Not Found

### ISSUE THREAD

**Issue by edwardr42000** [GetiPlayerAutomator/get-iplayer-automator#624]
I noticed the recent topic "'No shows found' (BBC) / 'Unknown: PID Not Found' / Web site down / Software updates broken/ Everything else that is wrong with GiA"

I am using Get Iplayer Automator for Mac.  I've tried the options in the topic but am still having the problem "PID not found"

I've tried Preferences> Unticking Quick Caching and then Force Cache update and also Check for Cache update but nothing has worked.  ITV Player still works.

Any ideas?

**Comment by Radar68** [comment]
Resolved my issue by disabling quick cache and then forcing a cache refresh.  Downloads now back working.

**Comment by edwardr42000** [comment]
Thanks Radar68 - I disabled quick cache and then forced a cache refresh.  The first time I tried this it didn't work, hence my post.  So I tried again and it worked.  Thanks conflictjohn and Radar68 for replying.

**Comment by dinkypumpkin** [comment]
Closed by #631
