### ISSUE TITLE
ERROR: Programe Type '' does not exist

### ISSUE THREAD

**Issue by goluxgolux** [GetiPlayerAutomator/get-iplayer-automator#626]
What steps will reproduce the problem? Be specific, and provide as much detail as possible.
Launch GiA, let it find BBC radio programme listed in PVR, click Start
What is the expected output? What do you see instead?
Expect download. Get error message "Download failed - Problem Unknown"
What version of GiA are you using? On what version of OS X?
GiA 1.8.7 (1793)          OS X version 10.8.5 
Are you using a web proxy? DNS proxy? VPN? VPS?
No  No  No  No
What programme are you attempting to download (full title, series and episode)? **Provide only ONE programme as an example. DO NOT list multiple programmes.**
The Real Comedy Controllers: The Things That Made Us Laugh - Alternative Comedy...and Beyond
If you cannot download a programme, provide a verbose log of the attempt. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE programme. DO NOT post a massive log covering multiple multiple programme downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

Please provide any additional information below.

**Comment by goluxgolux** [comment]
This problem arose a few days ago after GiA had worked beautifully for years. I haven't made any changes to my system so it's a mystery why GiA suddenly stopped working for no apparent reason.
The ERROR line in the Log said "Try using —refresh" so I tried File/Force Cache Update but this made no difference. I then uninstalled using DeleteApps to remove all associated files then made a clean install and tried again - still same problem.
P.S. I hope the Verbose Log uploaded OK, I don't see any sign of it.

**Comment by alexbird** [comment]
I have this issue. 

Using `get_iplayer.pl` directly, I initially got the same message, but after installing `rtmpdump` and `ffmpeg` my download worked. It still doesn't work in the automater UI, unfortunately.

**Comment by goluxgolux** [comment]
Hi Alex
Many thanks for your quick response. I have updated my ffmpeg, am now attempting to install rtmpdump… fingers crossed, I hope can do this!
cheers
Golux
 
-----Original Message-----

**Comment by Lordsnooty05** [comment]
I also have this issue with this Superb application. It has been running smoothly for yrs and then suddeningly about 3 days ago I couldn't record any programme from BBC or ITV. It just doesn't seem to be working and not only that I can't report the bug or issue. So I sought out this Forum to see if anyone can help or tell me how long before it is fixed. I know nothing about programming or anything technical. I just love this application for recording my favourite programmes from the BBC and ITV and I hope it is fixed soon. Can anyone tell me what is going on or can someone issue a patch or fix for this problem...Thanks



harry

**Comment by phildwuk** [comment]
I have the same issua as harry. Is this the end of a fantastic piece of software or is there a fix ? Help

**Comment by Lordsnooty05** [comment]
phildwuk  If you look down the other issues you will find a fix or way round the bug that is blighting this superb App. In the next few lines I will try and copy some of the comments that have helped me get this Application to work.....Thanks must go mostly to someone called Ghost but some others have helped. So here we go I hope it works for you as it does for me:-

First of all the reason there is this problem appears to be because the web site that provides the quick caching files is dead. It also provides software updates (there are no new updates, however), provided proxy settings, feedback handling, etc., so those are no longer working.

The way to get round this is to  go to Preferences/settings and go to quick caching(BBC Only) and UNCHECK it. then go to the Tab known as FILE and '**Force cache update**'

Also if you are in the UK don't use a proxy (Proxy = None in preferences). If you're not in the UK, you should be using a VPN instead of a proxy. I'm in the UK and I don't use a Proxy.

This has worked for me and I hope it works for you......mainly it is '**Force cache update**'

**Comment by phildwuk** [comment]
Lordsnooty05 thanks for your help. Have done as you say and it has improved (identifying PID etc) but I still get the maessage unknown bug. I have followed your instructions - removed BBC cache check,not using proxy, processing PID brings up the title, use Force cache update but then on start it goes straight to the error message "unknown bug" Should I reinstall? If so where is the best link?
Again many thanks for your help

Phildwuk

**Comment by Lordsnooty05** [comment]
phildwuk, as i said before I don't know anything about programming or how this application is put together. I have just read the notes on the other issues and put them together to come up with a fix for me. What works for me is **'Force cache update'**. How I record a program may help. I go to safari and go to the iPlayer website and then go to the program I want to record. Then I open GIA Application.......then **'Force cache update'** then click on the "Use Current Webpage" that loads the program in the Application and then I click on the start Button and the app records the program. From time to time I go to the Tabs and go to **FILE** and scroll down to **"Edit Download History"** and delete any programs that may be giving me trouble to download. I don't use the PID. I hope this might help. I hope someone from this Forum comes to my help as I am giving my opinions on what works for me. If you want to know more you will have to open a new Issue and see if anyone comes to your help. I know this is not a permanent Fix but only stop gap until either the Developer or someone on here sorts the problem out and I hope that is soon

**Comment by PeterinWales** [comment]
Thanks Lordsnooty05

Your fix works for me.  I have successfully downloaded BBC Radio programmes

**Comment by Lordsnooty05** [comment]
PeterinWales......Great news....I hope it continues to work and I hope the Developer gets his Website back and working

**Comment by dinkypumpkin** [comment]
Closed by #631
