### ISSUE TITLE
Not detecting open ITVHub page

### ISSUE THREAD

**Issue by BemusedOne** [GetiPlayerAutomator/get-iplayer-automator#627]
I have an ITV hub page open (it's the only window), but when I click use current webpage, GIA says I don't have a valid page open. It works fine with the BBC.

**Comment by Moisie2000** [comment]
Same here. Usually works - but not this evening.
GiA 1.8.7.

**Comment by dinkypumpkin** [comment]
ITV URLs have changed. This will require a new build to fix. There is no workaround.

**Comment by Mac-Man-APH** [comment]
At least you know what the problem is so where will the new build be located as old link to beta version has disappeared?

**Comment by erikmh** [comment]
Looks like ITV is now forcing https instead of http.

**Comment by petertribe** [comment]
I've done a pull request which should fix this bug...

https://github.com/GetiPlayerAutomator/get-iplayer-automator/pull/629

**Comment by robincm** [comment]
Where will we get this updated version please? - the "pre-" (beta) version site seems to have disappeared.

**Comment by bevanting** [comment]
Hi, newbie here. I'm also interested in finding this updated version. Thank you.

**Comment by naq59** [comment]
I´d also really appreciate a fix for this ITV change. Many thanks in advance

**Comment by tjdj1** [comment]
this older version works 1.8.4 here is a link     https://github.com/GetiPlayerAutomator/get-iplayer-automator/releases

**Comment by naq59** [comment]
Unfortunately I can´t get 1.8.4 to work with ITV here

**Comment by dinkypumpkin** [comment]
You shouldn't need to go back further than 1.8.6 to get the old ITV functionality.

**Comment by erikmh** [comment]
> "Use Current Webpage" still won't work for ITV, but you probably won't need it.

Umm. How else can you queue anything up for download? "Use Current Webpage" is vital functionality.

**Comment by dinkypumpkin** [comment]
Not if you have rolled back to 1.8.6 and thus restored the old ITV functionality, which once again gives you a searchable cache of ITV programmes. That assumes you leave Quick Caching deselected in Preferences, which is the only way GiA works at the moment.

**Comment by naq59** [comment]
That´s correct, using the search function it works again. Thanks for the tip. Will there be a new version at some point to re-enable the Current Website function?

**Comment by erikmh** [comment]
Yes, @dinkypumpkin, thanks for the instructions. I can’t say I’m a fan (several extra steps, and it’s much harder to figure out whether an episode is the one I want) — but it’s obviously *much* better than no work-around at all. I look forward to a release with @petertribe’s update.

**Comment by tjdj1** [comment]
Sorry forgot to say just use normal search for itv and it works not webpage

**Comment by hugofalkman** [comment]
Thanks madkub and dinkypumpkin. After merge of pull request #630  I cloned source and built release in Xcode. Works fine. 😉

**Comment by dinkypumpkin** [comment]
Closed by #631
