### ISSUE TITLE
Can't Download any BBC content

### ISSUE THREAD

**Issue by blightedplanet** [GetiPlayerAutomator/get-iplayer-automator#628]
Whenever I attempt to make a download I get the following: None of the download formats you specified were available for this show. Please add more download formats to your list of preferences. Any ideas how to fix this? Everything looks okay in the preferences panel. Thank you.

**Comment by fabmini** [comment]
I had the same problem this morning.
Usually I download in high quality, but when I added very high quality and HD to the list of format preferences, the download started to work again.

**Comment by murburz** [comment]
Having this problem with some ITV shows

**Comment by amlmd181** [comment]
I also am having problems with ITV downloads and getting the message "None of the download formats you specified were available for this show. Please add more download formats to your list of preferences."  What's changed and how can it be fixed?

**Comment by Lordsnooty05** [comment]
amlmd181....Scott knows about the problem and is already on the case. Obviously, this is a holiday period but he has said on another thread that he is going to try and fix it. It is working a 100% on BBC but not on some programmes on ITV Hub. Just to let you know while Scott is working on this problem you could try an Application called "Downie" (which someone has left a  link on another thread). Please be patient while Scott has his holiday and then finds the time to fix the problem....thanks

Here is the other thread 
https://github.com/Ascoware/get-iplayer-automator/issues/95#issuecomment-354328107

**Comment by amlmd181** [comment]
Thanks.  I found the other thread.
