### ISSUE TITLE
GiA BBC support is dead: Unable to download iPlayer programmes

### ISSUE THREAD

**Issue by botchla** [GetiPlayerAutomator/get-iplayer-automator#632]
What steps will reproduce the problem? Be specific, and provide as much detail as possible.
_Using the app as normal today, none of the settings have been changed, but I am getting failed downloads every time I try._

What is the expected output? What do you see instead?
_I expect the download to happen, and then a 'success' message. Instead, I get an error saying "Show could not be located." No proxy is being used, and I'm in the UK._ 

What version of GiA are you using? On what version of OS X?
_Using the latest pre-release, but I also rolled back to the one before that and the problem persists. Using OS X El Capitan 10.11.6_

Are you using a web proxy? DNS proxy? VPN? VPS?
_None of these._

What programme are you attempting to download (full title, series and episode)? **Provide only ONE programme as an example. DO NOT list multiple programmes.**
_The News Quiz: Series 93, episode 1. http://www.bbc.co.uk/programmes/b08mdjyb_

If you cannot download a programme, provide a verbose log of the attempt. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE programme. DO NOT post a massive log covering multiple multiple programme downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**
_Pastebin: [https://pastebin.com/kiHKcGVE](https://pastebin.com/kiHKcGVE)_

**Comment by erikmh** [comment]
I get the same exact results as @botchla with 1.8.8-pre.5. I can provide verbose logs if they’d be helpful, but they look essentially identical to those posted above via Pastebin.

**Comment by dinkypumpkin** [comment]
The BBC have just made the cull of data sources I warned about in #631.  BBC support in GiA is now dead.

You can read the BBC announcement at this URL (among others):

http://www.bbc.co.uk/programmes/b08mdjyb.xml

**Comment by MatzFan** [comment]
BBC were bound to withdraw access via apps eventually. Many thanks to @dinkypumpkin and all other GiA contributors for making BBC content available over the years.

**Comment by mothyinuk** [comment]
Can you direct me to the beta download site as GiA is having problems at the moment and it would be good to try beta versions, thanks.

**Comment by Lordsnooty05** [comment]
Oh dear that is all bad news. dinkypumpkin's new version I tried last night and it worked a treat but then I got news that this version was also not working. I tried it this afternoon and yes it isn't working. Oh dear what do we do now. Hopefully dinkypumpkin is right when he says that get-iplayer will be updated soon but that means me going back to Windows again. I suppose beggars can't be choosers

**Comment by user182015** [comment]
@Lordsnooty05 What software do you use on Windows?

**Comment by Lordsnooty05** [comment]
user182015 I haven't used it in a long time because I am mainly a Mac user but I have a couple of old PCs and a newish i7 laptop with Windows 10 on it......so I might give it a chance and try it out and it is called get_iplayer https://squarepenguin.co.uk/downloads/      although it appears from the forum it isn't working either

**Comment by dinkypumpkin** [comment]
The updated get_iplayer will work fine on macOS, just as it always has. It works the same on all platforms.

**Comment by Lordsnooty05** [comment]
Thanks as usual dinkypumkin......I'll try it on mac first and let you know. Also thanks for all your work on GIA and especial release yesterday which worked for a couple hours untill the BBC put paid to it.

**Comment by mutantcamel** [comment]
Well all good things...This app was a godsend as I'm in China for the forseeable future. Nice to see that get_iplayer will soldier on, the Web PVR looks like it's the way forward :)

**Comment by grafxflow** [comment]
Isn't it a case of changing their feed with the extension json instead of xml?

**Comment by ElsonRoa** [comment]
**Dinkypumpkin**, I second **MatzFan**’s thanks - I greatly appreciate your work on Get Iplayer Automator. 

When the BBC temporarily dropped its data services a few weeks back you also mentioned get_iplayer, and following your links and other instructions I learned how to get it running on my Mac via Homebrew. This was my first time to install software this way and I enjoyed learning a new skill.

Thank you again ~ your work is truly appreciated and admired

**Comment by hugofalkman** [comment]
Ok I managed to download Hinterland Episode 4 part 1 and 2 from BBC iPlayer:
Working from the command line (Terminal app in MacOS)  a one line install of get_iplayer
1. $ brew install dinkypumpkin/get_iplayer/get_iplayer
If it complains that brew is an unknown object you first need to install the (Home)brew package from
0. https://brew.sh/
2. To download the Hinterland episode another oneliner: $ get_iplayer --pid b08ntkk6,b08nx7g2 
An easy way to get the pid numbers is the "use current webpage" button in GiA which will display the pid numbers.
3. In iTunes use the Add to Library option in the file menu to import the .mp4 files. Then right click and choose Get info to build the metadata that was lost.
4. To download the subtitle track another oneliner in Terminal: $ get_iplayer --pid b08ntkk6,b08nx7g2 --subtitles-only . Add the subtitle tracks to the iTunes .mp4 files using Subler as usual.

**Comment by dinkypumpkin** [comment]
FYI: Subtitles can be downloaded along with the programme by using the --subtitles option

get_iplayer newcomers will find copious amounts of information at:

https://squarepenguin.co.uk/downloads/mac-os-x/
https://squarepenguin.co.uk/guides/
https://squarepenguin.co.uk/wiki/

However, I urge you in the strongest possible terms to wait until get_iplayer has been updated before attempting to use it. A lot of functionality is broken, and newcomers should really start with a working version.

**Comment by Lordsnooty05** [comment]
Hugofalkman, I tried doing what you stated and it didn't work. I did it exactly the way you stated and tried to download the Hinterland and it didn't work. So I think dinkypumpkin is right, we all should wait until Getiplayer is updated before attempting any future downloads.

**Comment by Beechside** [comment]
I know that dinkypumpkin does not accept money so the best I can do is give him my respect, thanks and envy for his skills and commitment.

Assuming that dinkypumpkin is actually a "he", that is...

**Comment by dvioletta** [comment]
Thanks very much both for keeping on top of the comments here and the updates you are doing dinkypumpkin.
I have been a long term user of GIA as it included radio services as well which few other ever did.
I will eagerly await the new version and try out the other solutions as required.

**Comment by martine14** [comment]
Thanks hugofalkman. Was trying to download the last episode of Hinterland and with the combination of the home-brew and GiA installation instructions using Terminal here, https://squarepenguin.co.uk/downloads/mac-os-x/, and your instructions it all worked fine. I did also follow dinkypumpkin's advice about --subtitles and seems to have downloaded with the subs as well. Obviously not as easy as using GiA, but not too bad if you don't have to do it too often. Thanks to all for their help and advice.

**Comment by reded247** [comment]
I just downloaded GIA 1.8.8pre.5. Works ok on ITV dosen't have the latest ITV programs but you use current web page do download the latest shows. Hopefully a new version will be released soon.

**Comment by reded247** [comment]
Hi there,
Thank you for fixing Iplayer Automater. I have copied Homebrew into
terminal and it has installed. I then copie the line:
dinkypumpkin/get_iplayer/get_iplayer.

But nothing happens, really hope you can help.

Thanks.

**Comment by wstiger** [comment]
Loaded get iplayer but did not realize that it was different from Get IPlayer Automator sorry for that.  Now I realize that get iplayer will only record programs and not put in ITunes.  Problem with that is that now they will only play on the Mac and not be on say an Apple TV to play on the TV.  Thats unless you have a Mac that supports Airplay.  Are there other methods of getting the recorded item into ITunes.

**Comment by chewitt** [comment]
Select files in Finder, click mouse button and drag/drop to iTunes, release mouse button. It's one of those "not rocket science" things.

**Comment by wstiger** [comment]
Ok thanks you are right not rocket science.

**Comment by reded247** [comment]
Or use software called beamer,i use on my mac.

**Comment by Lordsnooty05** [comment]
reded247 says he can get ITV programs on GIA .......I dont know about anyone else but I cant get anything to download on GIA....anyone else agree? I can get GetiPlayer to work on my Mac but it on retreives BBC programs, which is good but as good as GIA but I suppose 'beggars cant be choosers'. Does anyone know know how to create an icon for Mac for GetiPlayer instead of using Terminal all the time to start GetiPlayer?
Thanks

**Comment by reded247** [comment]
I an using GIA 1.8.8pre5, you can only download ITV program by using. Use
curret webpage. Works ok for me.

**Comment by martine14** [comment]
Just tried an ITV show from yesterday and it searched the Index and downloaded just like it should. A shame it doesn't work on iPlayer still, but at least GetiPlayer does and as Lordsnooty says, we can't be too choosy about that and I quite enjoy the simplicity of using it through terminal.

**Comment by LFS1** [comment]
As stated earlier by @dinkypumpkin you can download the pre-release version, probably easiest to turn off BBC and turn on alternative ITV index in advance tab then it should work fine for ITV only. 

I am starting work on bringing back BBC and it will take a while. I am hoping that as and when I am ready to issue a PR that @dinkypumpkin will be available to help with that.

**Comment by hugofalkman** [comment]
Great news LFS1. Thank you for starting on the project to restore BBC in GiA. Am sure dinkypumpkin will help with guidance once you submit the first PR.

**Comment by TomStenson** [comment]
Yes, great news LFS1! I've succeeded in installing and getting get_iplayer to work (thanks for all your work, dinkypumpkin), but I would much prefer not to have to use Terminal to download BBC programmes. That kind of MS-DOS type command line computing I happily left behind in 1986, when I got my first Mac!

**Comment by dinkypumpkin** [comment]
Sorry @LFS1, you will be on your own. As I said in #631, I have made my last contribution to GiA. Anyone who wants to come over to get_iplayer's wonderful world of the command line and web gui is welcome. Otherwise, give @LFS1 your support.

If you are going to put in the work to restore BBC functionality, then I suggest you fork the GiA repo and use that as the basis for any future releases. No PRs - build it the way you want. in my view, GiA's author has abdicated the right to complain about a "hostile" fork, but the way forward is yours to decide. You don't need to replace any of the release machinery he implemented (signed builds, Sparkle, etc.), or any of the tom-tech.com services. Just use the GitHub release system for distributing builds.

Actually, there is one bit of help I will give you if needed. When you demonstrate that you have re-integrated get_iplayer into GiA, I will show you how to modify it so that ITV search will work, if you can't figure it out yourself. In the same vein, you should be able to see which commits of mine to reverse in order to make your ITV indexing the default (and only) option. There is no point in keeping the old indexing method if there is no quick caching.

**Comment by LFS1** [comment]
Thanks for the offer @dinkypumpkin and for sure your help with getting the ITV options back in to get_iplayer will be very welcome. I'll reach out again when I get to the point of having something credible to demonstrate.

**Comment by MacMuser** [comment]
@LFS1 When you get GiA running, I'm sure there will be plenty of us who will gladly cover your essential supplies, beer, wine, chips…

**Comment by Lordsnooty05** [comment]
Great news LFS1.....thanks for this. Hopefully someone will help you complete the task of having GIA up and running with BBC and ITV programmes. Thanks also for helping me get GIA working for ITV.....I was able to download the fabulous "Little Boy Blue". Anybody able to answer the question about getting an Icon for a quick start for GetiPlayer to run for Mac Users instead of using Terminal, or can it be done?

**Comment by Rock-Hunter** [comment]
A lot of what is written on here goes straight over my head, I'm no programmer...however, I've really appreciated the time & effort put in by @dinkypumpkin and others over the years, this has been one fantastic program and it's a shame it no longer works. I wish @LFS1 all the best in restoring GiA to its former glory and I'm sure like many others I'd be willing to pay for a future working version.

**Comment by mh57** [comment]
I would like to echo Rock-Hunter's comments and thank @dinkypumpkin and crew for this extremely useful software, that I would willingly pay for. I wish the new crew my thanks for raising the new software.

**Comment by Themanwithoutaplan** [comment]
FWIW much as I love both get_iplayer and automator, I'm tempted to write something using Kivy.

**Comment by petermok** [comment]
My thanks to @dinkypumpkin and crew for this extremely useful software, that I would willingly pay for a new version that works.

**Comment by matthewrfox** [comment]
I'd also gladly pay for a working version. I even created a GitHib account to comment this. That's how serious I am :)

**Comment by Lordsnooty05** [comment]
Like others on here I would gladly pay for an App just like GIA which has worked so brilliantly for me for years. The positive news is GIA is working for ITV programmes so all we need is for it to work for BBC programmes. Also other  good news is LSF1 is working on GIA to either change it or improve it. Just a pity that the original programmer wouldn't come back and help him or Dinkypumpkin but they have their reasons

**Comment by UbiGit** [comment]
Many thanks to @dinkypumpkin and partners for their extraordinary efforts to keep us fed with BBC and ITV output for so many years. I would love to see a Phoenix rise from these particular ashes, one I would be happy to commit to with a purchase.

**Comment by SwaleSwimmer** [comment]
I must add my contribution. I used get iplayer on my PC and was delighted to be able to use GIA on my Mac. I used it daily. Like others I would be happy to pay for GIA. I just hope that by showing support it will encourage the programmers to keep going. Many many thanks to all the contributors.

**Comment by reded247** [comment]
Same here, i would be happy to pay for next version of GIA.

**Comment by Beechside** [comment]
We need to be careful here.  There is a big difference between paying for a tool that downloads copyrighted material and dropping voluntary payments into a donations box.  I would happily do the latter but the former could be causing trouble both for the dev and anybody purchasing a licence...

There's a reason why @dinkypumpkin doesn't accept payments, and I wonder if s/he would be prepared to disclose it?

**Comment by gingerbeardman** [comment]
Also, I'm not sure of the legalities of selling software that contains other open source software?

**Comment by Themanwithoutaplan** [comment]
@gingerbeardaman There is absolutely no problem with charging for open source software, whether it's your own or someone else's that has been packaged. The important thing are to respect the copyright and the licence.

Beechside raises a separate issue in that benefitting financially from the distribution of copyrighted material is illegal in some jurisdictions. IANAL but it's often best to avoid going near such discussions. It also tends to give the copyright lobby a hammer for platforms like I-Player.

A tipjar would avoid such problems.

**Comment by salbenedetto** [comment]
Just want to add my ha'porth. GiA has been a brilliant addition and I would happily contribute to any tipjar going.

**Comment by rogercuthbert** [comment]
Maybe a silly question, but what is behind the ITV downloads that now are showing again in the search in GiA? Can these also be downloaded using the underlying get_iplayer command line process.

**Comment by mutantcamel** [comment]
BBC has removed the data sources from their server that GiA uses to download BBC programmes, but ITV shows aren't affected.

**Comment by rogercuthbert** [comment]
Ok, yes I understand that. Does GiA use a different way of getting the ITV programmes then?  For BBC it uses the get_iplayer code. What doe it use for ITV?

**Comment by Roalnderson** [comment]
I'm glad I found this thread to keep up to date on what is happening. I really hope LFS1 is successful!!! Miss the app terribly!!

**Comment by skovatch** [comment]
I will be making a fork as well... I have BBC show downloads working right now, and will try to post an updated build within a week. I spent the last two days modernizing the code and reworking how the output is parsed -- get_iplayer has different output now for progress and completion, and the included version of ffmpeg is out of date. But I successfully fetched tonight's Doctor Who, and verified it converted. I had to manually add it to iTunes, but I'm working on that.

**Comment by botchla** [comment]
Hi @skovatch, that's great news and I won't be alone in appreciating your efforts - will you post here to let everyone know when you've done a build?

**Comment by Rock-Hunter** [comment]
Great news from @skovatch, really appreciate your efforts.

**Comment by mh57** [comment]
Complete techno-babble to me, but I am very appreciative of the work to keep the software working. Thank you @skovatch

**Comment by Roalnderson** [comment]
Fantastic!!! @skovatch

**Comment by moshimoshiii** [comment]
great news, appreciate your efforts @skovatch !!

If I can make one humble request - please keep this software compatible with older OSX versions (I'm on 10.8.5)

**Comment by Lordsnooty05** [comment]
Absolutely Great News from Scott Kovatch......so looking forward to trying out this build......also thank you to LSF1 for his build......it's a pity the two of you couldn't work together to come with a SUPERB build but hey beggars can't be choosers and I am sure I speak for all of us here that we appreciate all your efforts to resurrect this great app. I hope you let us all know of the new builds on this Forum in the absence to a dedicated Forum for GIA....thanks

**Comment by skovatch** [comment]
Okay, I have a build that works.
https://github.com/Ascoware/get-iplayer-automator/releases/tag/v1.9b1
Get a zip of it here, and let me know how it's going. I just downloaded a full list of 7 BBC shows, and I verified that ITV downloads also still work, although you need to use the "Use Current Webpage" button for the show you want.

**Comment by jeanpaulz85** [comment]
Hi Skovatch

I was not able to download GIA, could you explain how to do it.
Thanks

**Comment by skovatch** [comment]
See my edited comment -- you should get a button telling you to download a zip file.

**Comment by jeanpaulz85** [comment]
Thanks I got it  eventually, now I am checking if it works with me

**Comment by jeanpaulz85** [comment]
Did it take you a long time for the indexing of the programmes?

**Comment by jeanpaulz85** [comment]
Thanks Skovatch it is downloading, you are the best!!!!!

**Comment by nickp-ca** [comment]
Skovatch: Working for me - though index isn't - Use Current Webpage capture works.  Had to turn off all checkmarks under preferences, Items to Cache

**Comment by jeanpaulz85** [comment]
Thanks a lot

**Comment by rogercuthbert** [comment]
Great news.  Downloaded and tried and all working for BBC.  Don't know if it helps but the search and download was working OK on ITV showsin Version 1.8.8-pre.5 (1811).  i.e. didn't need t use the Current Webpage to get ITV progs.

**Comment by SwaleSwimmer** [comment]
So pleased - Skovatch -thank you for your great effort. Busily downloading Beeb and ITV right now.

**Comment by dinkypumpkin** [comment]
@skovatch - you violated GiA's licence by releasing the application to the public without making your source code available. That is a definite no-no, as you should know. I have removed your download link and locked this ticket until you post your code. Sorry folks, but this is a serious matter for open source developers.

**Comment by dinkypumpkin** [comment]
All discussion should now go to:
https://github.com/Ascoware/get-iplayer-automator/issues/1
