### ISSUE TITLE
GiA information request

### ISSUE THREAD

**Issue by Necktilt** [GetiPlayerAutomator/get-iplayer-automator#633]
You say ....

**This issue tracker is not a discussion forum, so don't use it as such.  If you wish to discuss the BBC, iPlayer or anything else that is not related to an actual problem with the current release of GiA, post in an appropriate forum, not in this issue tracker.**

So where do I post if I want ask about the future of GiA?

**Comment by Necktilt** [comment]
OK ... I'll interpret the silence as it's OK to post here.

I’ve used Get iPlayer Automator for a while now on OSX (and more recently MacOS) and it’s a useful and important app for me. I was shocked to see it get broken recently after the BBC’s moves. I’m confused about who does what around here, but may I have some info on the potential future of GiA?

I am not an overly technical person, just someone who has depended on GiA over the years. As I understand it, GiA relies on Get iPlayer and is in effect a front-end for that app. I think I’m correct in saying that “dinky” is responsible for Get iPlayer. I’m not clear about who is responsible for GiA, but maybe “dinkypumpkin”? Presumably related?

Can anyone confirm who is responsible for GiA, and can they tell us what the plans are, if any, for that app? I don’t want to tread on any toes and, again, if I'm in the wrong place, please direct me to the right one. I’d just like to know if there’s any chance of getting a clearer idea of what’s happening with GiA, ideally from the person who develops the app or at least has a good idea of the situation.

Thank you!

**Comment by tracer-x1** [comment]
I think there has been some significant changes.   There is a post (631)  that describes that there were some changes at the BBC. And the kind person who was doing the programming has understandably stopped.  Someone else would need to take up the banner-so my understanding is, at the moment, the latest is as good as it can be and the future is uncertain.

**Comment by Necktilt** [comment]
Thanks tracer-x1. As I understand it, the changes at the BBC have broken GiA, so rather than being what you call "as good as it can be", it is in fact not working at all. What I'm trying to find out is, given that Get iPlayer seems now to have been fixed, will GiA also be fixed? I wonder if this is the place to get an answer, or if there is another forum where someone knows what's going on?

**Comment by larryy** [comment]
The previous developer, dinkypumpkin, has said he is done with GiA.  However, someone else said he was going to try to fix it, and I believe that person has submitted code to GiA in the past, so there's some hope it will actually happen.  But that's all anybody knows.  Go read that other thread tracer-x1 pointed you to if you want the rest of the context.

**Comment by Necktilt** [comment]
Thanks larryy. I had read post 631 before I posted here, which was useful, but it didn't give any clues about who might be updating GiA, only that it wouldn't be the poster. Is it possible to contact or find the "someone else" you mention?

**Comment by larryy** [comment]
Sorry, it's 632 that actually has the long thread in which the "someone else" announced his or her intentions.  And it's @LFS1.

**Comment by Necktilt** [comment]
Thanks larryy. Post 632 wasn't so advanced when I posted, but now, that seems to be the one to keep an eye on for developments. I'll do so!

**Comment by gingerbeardman** [comment]
So @skovatch has a new build with source code here: https://github.com/skovatch/get-iplayer-automator

**Comment by gingerbeardman** [comment]
New build here: https://github.com/Ascoware/get-iplayer-automator/
