### ISSUE TITLE
Transfer control of this account/org repo?

### ISSUE THREAD

**Issue by chewitt** [GetiPlayerAutomator/get-iplayer-automator#636]
@dinkypumpkin is there a long-term plan to transfer control of this "name" github account (or is it an org) to the people who emerge as the caretakers of this app? Forking to another repo is fine for coding but I always think it looks sad when the original 'upstream' location for a project that carries it's name gets abandoned. If it's a case of time/effort to deal with n00bs posting +1 issue posts here I would be happy to act as a neutral guardian while others who code pick up the baton of development. I'm already involved in the activities of two large/major projects (one that I run directly) and I'm familiar with such responsibilities.

**Comment by dinkypumpkin** [comment]
Feel free to redirect errant travellers if you like, but I wouldn't expect many. This tracker never got much traffic . The new people will have to chase GiA's author to resolve the fate of this repo.
