### ISSUE TITLE
Downloading Autodescribed Versions from BBC - how do I stop it?

### ISSUE THREAD

**Issue by darfielddx** [GetiPlayerAutomator/get-iplayer-automator#637]
When downloading BBC programmes, I am getting the autodescribed versions, which I find particularly annoying. In preferences I do not have the autodescribed downloads option ticked (at the bottom). Is there any way to avoid this type of download?

**Comment by Vangelis66** [comment]
@darfielddx 

Which part of https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues/635 is unclear to you? :confused: :-1: 
Please close...

**Comment by darfielddx** [comment]
Thank you for your positive reply. I thought I was on the other site. I am not technically minded! Are you always this sarcastic?
