### ISSUE TITLE
Support link for this repo points to a malware site

### ISSUE THREAD

**Issue by madwort** [GetiPlayerAutomator/get-iplayer-automator#638]
This github repo still comes up on searches, and the link at the top of the page to HTTP-tom-tech.com/iplayer appears to go to a malware site, could this link be removed?

**Comment by gingerbeardman** [comment]
It would also be great if this repo could be made read-only

**Comment by willson556** [comment]
Thanks! Removed and made more clear this repo is no longer maintained.
