### ISSUE TITLE
Can't download from new BBC Sounds page, was possible with earlier BBC iPlayer Radio

### ISSUE THREAD

**Issue by mgoeppl** [GetiPlayerAutomator/get-iplayer-automator#639]
What steps will reproduce the problem? Be specific, and provide as much detail as possible.
I can't download BBC Sounds programmes.

What is the expected output? What do you see instead?
It returns the infamous "Programme Page Not Found" error. 

What version of GiA are you using? On what version of OS X?
GiA 1.13.16 (20181016001)
macOS 10.14.1 Beta (18B57c)

Are you using a web proxy? DNS proxy? VPN? VPS?
VPN, yes. But downloading shows does work like a charm. 

What programme are you attempting to download (full title, series and episode)?
https://www.bbc.co.uk/sounds/play/p06pbbdm

Please provide any additional information below.

**Comment by gingerbeardman** [comment]
Wrong repo, please post here: https://github.com/Ascoware/get-iplayer-automator/issues
